### ISSUE TITLE
Names not populated in `Bracing Night` scheduling

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#101]
## Describe the bug
When scheduling `bracing_night` messages, `guardian1_first_name` is not being populated in the messages, even though it’s fetched correctly from Salesforce. 

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/miraclefeet/runs/061adc6d-a4fa-7218-a39d-f6ade3279d15

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/2.scheduleContactSMS.js

### state.json

See LP for `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

### adaptor

`language-salesforce`, `language-http`

## To test/resolve
Please test the change on OpenFn.org by re-running this run https://www.openfn.org/projects/miraclefeet/runs/061adc6d-7a82-7dba-b801-4b404c827b25 (parent run for failed run)  and confirming success.

**Comment by lakhassane** [comment]
@ritazagoni the mapping object was incorrectly updated. It's fixed now. Check run: https://www.openfn.org/projects/miraclefeet/runs/061adf33-c886-72ea-a0b6-075931abb175

**Comment by aleksa-krolls** [comment]
Thanks, @lakhassane. 
@ritazagoni on Weds... please re-test and make sure all the SMSs looking good. If yes, let's push to go-live.

**Comment by ritazagoni** [comment]
Looking all good.
