### ISSUE TITLE
Deactivation: Query for `Contact`-s doesn't return expected Contacts

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#102]
## Describe the bug
In [getInactiveClinics](https://github.com/OpenFn/Miracle-Feet/blob/0635a1acb769a9d30d440e05a4e2c097acc06602/getInactiveClinics.js#L1-L14) we look for Contacts that are associated with Accounts in specific Status-es. Even though we find and log the correct Accounts, we don't seem to find the associated Contacts.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/miraclefeet/runs/061af4ad-2e0c-7a1e-a517-4f90d249a7ff We would expect to find 2 Contacts with Account `Test Clinic 2` and 2 Contacts with Account `Test Clinic 1`.

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/getInactiveClinics.js

## state.json
See LP for `MiracleFeet SMS Sandbox Salesforce` (contact AK to get verification) 
and `Infobip Portal (MiracleFeet)`

## adaptor
`language-salesforce`

## To test/resolve
Feel free to re-run https://www.openfn.org/projects/miraclefeet/runs/061af4ad-2e0c-7a1e-a517-4f90d249a7ff

Ping @ritazagoni with any questions

**Comment by lakhassane** [comment]
@ritazagoni I might need you in this to detail what is not right. The job does not do any filtering or something else. Are we sure those contacts exist?

**Comment by aleksa-krolls** [comment]
@lakhassane I think the logs are what is throwing us off. For example, why does L7 of [this run](https://www.openfn.org/projects/miraclefeet/runs/061af4ad-2e0c-7a1e-a517-4f90d249a7ff) show `{ totalSize: 0, done: true, records: [] }` ... this to means no records were returned. 
However, if I execute this query directly in SF, I see 4 Contacts are returned. 
<img width="1280" alt="Screen Shot 2021-12-07 at 9 52 52 PM" src="https://user-images.githubusercontent.com/16758106/145097070-77cad1dc-61cc-4c6f-ae96-5fd9fc1fb59b.png">

Can you please work with @ritazagoni tomorrow morning to make the logs more readable? Rita, please outline to Mamadou exactly what you want to see logged.

**Comment by aleksa-krolls** [comment]
HOLD UP @ritazagoni looks like MF switched the job to point to prod... is this what is tripping you up? 
https://www.openfn.org/projects/miraclefeet/jobs/jvn5rk
