### ISSUE TITLE
Only schedule bracing night messages if `Contact`-s `Account` is "Actively Supported" or "Temporarily Suspended"

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#107]
## The specific request, in as few words as possible

We want to schedule bracing night messages only if `Contact`-s `Account` is actively supported or temporarily suspended. In order to do this, we should add the following condition for fetching Salesforce `Contacts` 
IF `Account.Status__c  IN ("Actively Supported", "Temporarily Suspended" )` to the [Bracing-night fetch job](https://openfn.org/projects/miraclefeet/jobs/jv9qn9).

## state.json

See LP for  `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

## adaptor

`language-salesforce`, `language-http`

**Comment by ritazagoni** [comment]
hey @lakhassane  - this has been moved to Review/QA, could you confirm if it's ready to test?

**Comment by lakhassane** [comment]
@ritazagoni I think you moved it (by mistake?). I have not touched anything yet.

**Comment by lakhassane** [comment]
@ritazagoni this is now ready to go!
