### ISSUE TITLE
Schedule and cancel SMSs based on Salesforce `Treatment_Completed__c` field

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#108]
## Background, context, and business value
Original issue: #103 

When a patient completes treatment, it will appear in Salesforce as `Complete` in the `Account.SMS_Treatment__c` field.  
In this case we are sending Alert #13 and canceling SMS for `SMS_Original_Treatment__c` and for and alert 14, 15, 16 and reminders (Alert 17, 18). We want to keep this step and add as below.

We want to add the same scheduling and (slightly modified, see below) deletion steps based on the  `Account.Treatment_Completed__c` field as well.

## The specific request, in as few words as possible

Add the following logic to [schedule_smsv2.js](https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_smsV2.js):

When `Account.Treatment_Completed__c == true`:
1. **Schedule** [alert #13](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=379768061&range=107:107)
2. **Delete** alert for `SMS_Original_Treatment__c` and for `SMS_Treatment__c`  AND alert 14, 15, 16 AND reminders (Alert 17, 18)

## state.json

See LP for  `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

## adaptor

`language-salesforce`, `language-http`

**Comment by aleksa-krolls** [comment]
@ritazagoni is there existing logic for when `Account.SMS_Treatment__c = 'Completed'` that we are _changing_ to reference `Account.Treatment_Completed__c = true`? Or this entirely new logic we're inserting? (That isn't clear and is an important distinction.)

**Comment by lakhassane** [comment]
@ritazagoni I still have questions additionally to those from Aleksa.
Are we adding another logic to schedule alert 13 or a check between `SMS_Treatment__c` or `Treatment_Completed__c`?
Thies are 2 different things because if we just add the new logic we might (will) have duplicates on alert 13.

Also is the real columns `Account.SMS_Treatment__c` or just `SMS_Treatment__c` which is what we have been using so far?

**Comment by ritazagoni** [comment]
Good point @lakhassane on duplication.
Let's do this:
1. Remove current scheduling and deletion of Alert #13 based on condition `Account.SMS_Treatment__c == Complete` 
2. Add logic to 
When `Account.Treatment_Completed__c == true`:
1. **Schedule** [alert #13](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=379768061&range=107:107)
2. **Delete** alert for value of `Account.SMS_Original_Treatment__c`  AND alert 14, 15, 16 AND reminders (Alert 17, 18)

**Comment by lakhassane** [comment]
@ritazagoni thanks for the updates.

I made the change in the logic

**Comment by ritazagoni** [comment]
hey @lakhassane I got an error https://openfn.org/projects/miraclefeet/runs/061e6bf5-8de5-744d-bfad-cdff2d10edcd `TypeError [Error]: Cannot destructure property 'key' of 'alert' as it is undefined.` I think it's related to this change

**Comment by lakhassane** [comment]
@ritazagoni there was a typo in scheduling alerts. Find last run with correction: https://openfn.org/projects/miraclefeet/runs/061e705b-6873-78dc-bb6b-3b9806e3ead3

**Comment by ritazagoni** [comment]
hey @lakhassane can we make an adjustment to the deletion logic?

When `Account.Treatment_Completed__c == true`:
1. **Schedule** [alert #13](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=379768061&range=107:107) [**IMPLEMENTED**]
2. **Delete** alert for `SMS_Original_Treatment__c` if != "Complete" AND for `SMS_Treatment__c` if != "Complete"  AND alert 14, 15, 16 AND reminders (Alert 17, 18)

**Comment by lakhassane** [comment]
@ritazagoni I updated the logic of `Treatment_Completed__c` as this:
- We delete `original treatment` alert and `treatment` alert only when either one is different from 'Complete'

**Comment by ritazagoni** [comment]
@lakhassane can you check this run? https://openfn.org/projects/miraclefeet/runs/061e9033-4a7d-7a03-b2ad-12d26935b32e
From logs `L5`:
`Contact` `Jessica Jones`:
`originalTreatment: 'Casting',`
`treatment: 'Complete',`
`treatmentCompleted: true`

We would need to delete alerts for `originalTreatment: Casting`, but I think we're not deleting any alerts: logs `L1143`: `messages to delete []`

**Comment by ritazagoni** [comment]
hey @lakhassane we seem to have the opposite issue in this run https://openfn.org/projects/miraclefeet/runs/061e952c-cd0d-7d68-9d28-045f73d75415, from logs `L149`:
```
  Name: 'Patient C Test',
  originalTreatment: 'Casting',
  treatment: 'Casting',
  treatmentCompleted: false
```

In logs from `L214` we are canceling the `Casting` messages, but we should leave them unchanged.

Ping me for a chat if needed!

**Comment by lakhassane** [comment]
@ritazagoni the first one is solved.

For the second one there is this requirement from the data flow.

It says to delete `originalTreatment` if `treatment` is `'Casting'`. In this case originalTreatment being also 'Casting' it will get cancelled

<img width="256" alt="Screen Shot 2022-01-21 at 20 33 17" src="https://user-images.githubusercontent.com/8411231/150596372-ba863e49-b731-4842-b2b3-bf7e56c01348.png">

**Comment by ritazagoni** [comment]
Thanks @lakhassane !
And great point. I've updated the data flow chart:

**Comment by lakhassane** [comment]
Gotcha @ritazagoni.

I pushed that change
