### ISSUE TITLE
Filter fetching Accounts by `LastModifiedDate` date

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#109]
## Background, context, and business value
Original issue: #103

As the fetch job runs daily at 12AM, in the subsequent run we only want to fetch contacts that have been modified since the last run.

## The specific request, in as few words as possible

In [fetchContacts.js](https://github.com/OpenFn/Miracle-Feet/blob/master/fetchContacts.js) add the following logic to the Salesforce query:

Fetch contacts where `Account.LastModifiedDate` (dateTime) > Today()-1 12AM 

## state.json

See LP for  `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

## adaptor

`language-salesforce`, `language-http`

**Comment by aleksa-krolls** [comment]
@ritazagoni one question here... do we need to worry at all about the time zone of the platform vs. time zone of the salesforce system? (This might only affect how we configure our timer trigger to schedule the job, not the Salesforce query - but want to double check.)

**Comment by ritazagoni** [comment]
@aleksa-krolls Yes, this should be according to the platform time zone. How can I check the time zone of SF?

**Comment by aleksa-krolls** [comment]
@lakhassane when you work on this, see comments above. Wondering if you have thoughts on how to handle time zones and whether you can convert everything to UTC? cc @ritazagoni

**Comment by ritazagoni** [comment]
Reminder for @ritazagoni to verify and implement the same filter in getInactiveClinics.js

**Comment by lakhassane** [comment]
@ritazagoni I added a filter to fetch only contact where `lastModifiedDate` is greater than the previous day at `00:00`.
I don't think we need to worry about the timezone since we set to the previous date at 12AM

**Comment by aleksa-krolls** [comment]
@ritazagoni can we close this one? Looks like #111 has next steps
