### ISSUE TITLE
Only schedule SMS if `Account.Guardian_1_Phone_Landline__c == false`

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#110]
## Background, context, and business value
Original issue: #103

## The specific request, in as few words as possible
Add logic to [schedule_smsV2.js](https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_smsV2.js) to:

Only schedule SMS for a contact if `Account.Guardian_1_Phone_Landline__c == false`

## state.json

See LP for  `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

## adaptor

`language-salesforce`, `language-http`

**Comment by aleksa-krolls** [comment]
@ritazagoni I just want to gut check this one bc seems like a strange requirement (having no context)... if the guardian has a landline, then we _are_ scheduling SMSs? And does this apply to all SMSs?

**Comment by ritazagoni** [comment]
you're so right @aleksa-krolls

**Comment by lakhassane** [comment]
@ritazagoni I added the logic. This is ready for testing.
