### ISSUE TITLE
Add Salesforce queries to find `inventoryId` to map to Partner_Brace_Inventory__c

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#112]
## Request
We need to find parent SF records that don't have direct relationships in the data model. Can you please help me to implement these 2 Salesforce queries to get the `inventoryId`
https://github.com/OpenFn/Miracle-Feet/blob/53f9997b6330dacef08001b8c99856dfdd48e836/upsert_brace_inventory.js#L1-L5

This can this be used as the source value for the draft `Partner_Brace_Inventory__c` mapping on L44. 

## state
See LP for `MiracleFeet Salesforce Production`
Use this message: https://www.openfn.org/projects/miraclefeet/messages/06177a21-d0f8-70be-b3b7-51f8fc83c6c5

## expression
upsert_brace_inventory.js

## To test
If you run these 2 queries, I expect `inventoryId = 'a1U3l00000dP2wOEAS'`
https://castapp.lightning.force.com/lightning/r/Partner_Brace_Inventory__c/a1U3l00000dP2wOEAS/view

**Comment by lakhassane** [comment]
@aleksa-krolls fetching `inventoryId` successfully and mapping it. But there is a missing field you might need to check: `REQUIRED_FIELD_MISSING: Required fields are missing: [Patient__c]`
