### ISSUE TITLE
`schedule_sms` job fails with `400` error

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#114]
## Describe the bug
From Infobip API `Error: Request failed with status code 400`.
The error seem to be related to scheduling a message too far ahead: `  sendAt: '2022-08-11T09:00:56.257Z'` (see [run logs](https://www.openfn.org/projects/miraclefeet/runs/061f2332-680c-7c3c-9334-fca891d9d7eb) from `L236`).

We should only be scheduling [these bracing_night messages](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=49:55) in this job.

## To Reproduce
Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/miraclefeet/runs/061f2332-680c-7c3c-9334-fca891d9d7eb

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json
Example data: https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/log_visit_details_original_treatment.json
See config LP `Infobip Portal (MiracleFeet)`

### adaptor
`language-http`

## To test/resolve
You can test by re-running https://www.openfn.org/projects/miraclefeet/runs/061f2332-680c-7c3c-9334-fca891d9d7eb

**Comment by aleksa-krolls** [comment]
@lakhassane please prioritize this tomorrow

**Comment by ritazagoni** [comment]
@lakhassane as discussed, please use [this mappig](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=49:55) for scheduling bracing_night messages in the schedule_sms.js job.

**Comment by lakhassane** [comment]
@ritazagoni green check after updating the mapping object as discussed!
https://www.openfn.org/projects/miraclefeet/runs/061f3cd7-7620-7909-958d-6c4f2663583b
