### ISSUE TITLE
Consider the `schedule_smsV2.js` into 2 jobs

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#115]
## Background, context, and business value
Currently this job handles logic for both scheduling new alerts, as well as disabling alerts. As we scale, to minimize runtime and allow for 2 different Salesforce queries, let's consider: 
1. Flow 1: Where we fetch Contacts where SMS should be disabled --> then disable alerts
2. Flow 2: Where we fetch Contacts where SMS should be scheduled --> then schedule alerts

## state.json

Either provide state directly, or link to a file. If sensitive information
should be in state, redact it and provide instructions for where it can be
found.

```json
{
  "configuration": { "username": "abc", "password": "REDACTED" },
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```

```json
{
  "configuration": ["SEE LAST PASS: 'client cred'"],
  "data": { "a": 1 },
  "cursor": "2020-01-19 00:00:00"
}
```

## adaptor

List the adaptor to be used for this job. If changes must be made to the
adaptor, explain why existing functions dont work and specify the new API you'd
like from a helper function.

```md
There is no "upsert" in postgres. I'd like an API where I can provide the table,
the UUID, and some data to upsert. Like this:

upsert('some_table', 'some_column', state.data.records);
```

## expression.js

In pseudocode, either in the current job expression or in a new file, describe
as best you can what changes need to be made

```js
each(
  'state.data.patients[*]' // PLEASE FIND THE PATIENTS AND DO THIS FOR EACH ONE
  create('object', fields(
    field('name', state.data.name)
    field('age', '????????') // PLEASE CALCULATE AGE
  ))
)
```

## output.json

Either provide the output you'd like, or describe it in terms of final state and
side effects.

### side effects

1. upsert new records to postgres

### output.json

```json
{
  "configuration": {},
  "data": { "statusCode": 200 },
  "references": { "a": 1 }
}
```

**Comment by aleksa-krolls** [comment]
hey @ritazagoni did we solve for this already? Can we close this?

**Comment by aleksa-krolls** [comment]
@ritazagoni can we close this issue?

**Comment by ritazagoni** [comment]
Splitting the job into 2 was an idea we floated when some of the runs were long but never explored it further and we don't seem to have had issues since (long runs are now enabled for this job). Runs may be 4min+ currently, we would probably still need long jobs even with the new structure. We don't foresee any other/functional benefits. Rita and Aleksa to revisit after checking in with Miraclefeet on strategy and plans.
