### ISSUE TITLE
SMS Cancellation: TypeError [Error]: mapping[key] is not iterable

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#119]
## Describe the bug
Failing with type error `TypeError [Error]: mapping[key] is not iterable`
See run failure: https://www.openfn.org/projects/miraclefeet/runs/061fc545-21f5-7430-9992-f46c0b6aab38

## To Reproduce
1. Feel free to re-run on platform. 

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json
See LP `Infobip`
https://www.openfn.org/projects/miraclefeet/messages/061fc545-1816-7801-a9b7-8c1aca2cbcb5

**Comment by lakhassane** [comment]
@aleksa-krolls the mapping object in the job has been updated wrongly causing this issue.
I'm trying to correct but also there is a lot of mapping tabs in the sheet [here](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774) and it's easy to get lost.

Is it possible to separate the mapping sheets in different tabs with the right naming for every job that needs one (`schedule_sms.js`, `schedule_smsV2.js`, `2.scheduleContactSMS.js`)?
cc @ritazagoni

**Comment by lakhassane** [comment]
The issue is solved for this one https://www.openfn.org/projects/miraclefeet/runs/061fd047-1f57-76ee-affb-133bdff00b89

**Comment by aleksa-krolls** [comment]
@ritazagoni thoughts on what when wrong here, how we can better manage the mapping tables, and learnings for next time?

**Comment by aleksa-krolls** [comment]
@ritazagoni see my comment above (but I think you've addressed). Can we close this out then? :)

**Comment by ritazagoni** [comment]
Mapping sheets and readme updated!
