### ISSUE TITLE
Update_Patient: TypeError [Error]: Cannot read property 'case' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#121]
## Describe the bug
This job was working for ages, but suddenly today I'm seeing lots of runs for this job fail with the error message `TypeError [Error]: Cannot read property 'case' of undefined`
https://www.openfn.org/projects/miraclefeet/runs/06201243-0890-7645-a6ce-3db2a9fb4cf7

## To Reproduce
Feel free to re-run on platform, and/or switch adaptor versions as needed. 

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/update_patient_UPDATED.js

### state.json
SEE LP `MiracleFeet Salesforce Production`
https://www.openfn.org/projects/miraclefeet/messages/06201242-ff17-73c6-a536-2a707cef23bc

**Comment by lakhassane** [comment]
@aleksa-krolls I see this snippet of code has been added to the job
```
field('Date_of_SMS_Registration__c', state => {
          return state.dateConverter(
            state,
            state.data.form.case.update.date_of_sms_registration
          );
        }),
```

However this path (`state.data.form.case.update.date_of_sms_registration`) does not exist in any of the messages used. Could you double check? I will comment that part for now.

**Comment by aleksa-krolls** [comment]
@ritazagoni what is this `date_of_sms_registration`. See Mamadou's comment and advise on the mapping here. Also, did you recently make changes to the MF jobs? Everything is failing right now

Also @lakhassane I'm seeing a ton of failures with the same message on `Update_Visit_V2`... is there a similar issue going on? https://www.openfn.org/projects/miraclefeet/runs/062023c4-f5d5-7c40-bec2-9a4f173cf901

**Comment by aleksa-krolls** [comment]
Thanks @lakhassane. Feedback shared with the client
