### ISSUE TITLE
SMS: Process fetched contacts in batches

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#125]
## Background, context, and business value

In the SMS flow, we currently [fetch](https://github.com/OpenFn/Miracle-Feet/blob/master/fetchContacts.js) a number of contacts from Salesforce and pass `state` to the [SMS scheduling job](https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_smsV2.js) to schedule SMSs.

See jobs on the platform:
1. https://www.openfn.org/projects/miraclefeet/jobs/eZiygD
2. https://www.openfn.org/projects/miraclefeet/jobs/QjbQti

As the solution scales, we want to avoid hitting the Infobip API limit of 60 requests/min for the [get-sms](https://www.infobip.com/docs/api#channels/sms/get-scheduled-sms-messages-status) endpoint. We want to process fetched contacts _in smaller batches_, send them to the inbox, and run the scheduling job on the messages.

## The specific request, in as few words as possible

After the [fetch job](https://github.com/OpenFn/Miracle-Feet/blob/master/fetchContacts.js) fetches the contacts from Salesforce:
1. Divide the contacts to create messages of 30 contacts/message (e.g., if the SF query returns 60 contacts, create 2 Messages)
2. Tag messages with `tag: sms_salesforce`
3. Send the messages to the inbox

The scheduling [job](https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_smsV2.js) will then run as a message filter job instead of a flow job. Other than the trigger, no changes should be needed. 

## state.json

See LP for  `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

## adaptor

`language-salesforce`, `language-http`

**Comment by aleksa-krolls** [comment]
@ritazagoni wondering if this needs to be replicated for bracing_night? 
cc @lakhassane

**Comment by aleksa-krolls** [comment]
@lakhassane what was the approach you decided on here? 
cc @ritazagoni

**Comment by ritazagoni** [comment]
> @ritazagoni wondering if this needs to be replicated for bracing_night? cc @lakhassane

That's a good point @aleksa-krolls , yes, I'll create the issue

**Comment by lakhassane** [comment]
@aleksa-krolls Im on it currently. For now I go with the batch solution. Then we will see if there is a way to delay at least one get request. So in that case even if we can have 59requests/min it will still be okae.

**Comment by lakhassane** [comment]
@aleksa-krolls I made the splitting into batches. For now this is how it is represented: https://openfn.org/projects/miraclefeet/messages/0620e329-383a-787c-b886-7a760e507430

**Comment by ritazagoni** [comment]
hey @lakhassane I tried to run the scheduling job on the message and got this error: https://openfn.org/projects/miraclefeet/runs/0620f3cf-e05a-7539-a0f5-ff6fd2c5bdf5

**Comment by aleksa-krolls** [comment]
@lakhassane was this even tested locally? 

@ritazagoni I think I fixed with this commit: https://github.com/OpenFn/Miracle-Feet/commit/cd3b83e93ea18053e4e9ce69b03e36a8300ed074

See successful run: https://openfn.org/projects/miraclefeet/runs/0620f3e4-4f48-75c6-bbd5-5fae6c01d279
