### ISSUE TITLE
SMS: Process fetched contacts in batches for `bracing-night` flow

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#126]
## Background, context, and business value

See request for same functionality in SMS flow #125 

Fetch job: https://github.com/OpenFn/Miracle-Feet/blob/master/1.fetchContact.js (see [here ](https://www.openfn.org/projects/miraclefeet/jobs/jv9qn9)on platform)
Scheduling job: https://github.com/OpenFn/Miracle-Feet/blob/master/2.scheduleContactSMS.js (see [here](https://www.openfn.org/projects/miraclefeet/jobs/jvn5jk) on platform

## The specific request, in as few words as possible

After the [fetch job](https://github.com/OpenFn/Miracle-Feet/blob/master/1.fetchContact.js) fetches the contacts from Salesforce:
1. Divide the contacts to create messages of 30 contacts/message (e.g., if the SF query returns 60 contacts, create 2 Messages)
2. Tag messages with `tag: bracing_night_salesforce`
3. Send the messages to the inbox

The scheduling [job](https://github.com/OpenFn/Miracle-Feet/blob/master/2.scheduleContactSMS.js) will then run as a message filter job instead of a flow job. Other than the trigger, no changes should be needed. 

## state.json

See LP for  `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

## adaptor

`language-salesforce`, `language-http`

**Comment by aleksa-krolls** [comment]
@ritazagoni confirming that this is the _exact same_ request as #125 , just replicated in this bracing_night job? 

@lakhassane can you pls replicate those changes here as well?

**Comment by ritazagoni** [comment]
@aleksa-krolls @lakhassane yes, it is the exact same request

**Comment by lakhassane** [comment]
@ritazagoni I made the replication.

Just flagging you need to add `openfnInboxUrl` to the credentials (for #125 as well)
