### ISSUE TITLE
Update_Patient: `RangeError [Error]: Invalid time value`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#127]
## Describe the bug
Run is failing with the error `RangeError [Error]: Invalid time value`. I'm guess there is some unexpected data format in the CommCare source data. 

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/miraclefeet/runs/0620d20d-bd63-7f71-bc8e-ec2dc0bb8c10
Feel free to re-run on platform. 

### adaptor
salesforce

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/update_patient_UPDATED.js

This job is linked to here on platform: https://www.openfn.org/projects/miraclefeet/jobs/jyjaqq

### state.json
`configuration`: See LastPass for `MiracleFeet SMS Sandbox Salesforce`

`data`: 
Here is the source message that triggered the failure: https://www.openfn.org/projects/miraclefeet/messages/061fbee2-d0b5-72c7-8126-4928b83bddf7

## Expected behavior
Patient record should successfully be upserted in Salesforce. If you encounter any other errors besides this one, let me know before you continue troubleshooting.

**Comment by aleksa-krolls** [comment]
@lakhassane can you work with @grayey on this one tomorrow? When doing so, please shared the appropriate configuration details with him via Slack DM.

**Comment by grayey** [comment]
@aleksa-krolls We have solved the issue with the date. See run here: https://www.openfn.org/projects/miraclefeet/runs/0620e525-80ad-7c35-8edf-35c4e3ac187d

**Comment by aleksa-krolls** [comment]
thanks, @grayey looking good!

**Comment by aleksa-krolls** [comment]
@grayey I'm seeing this same time error surface again on more recent data processed. Can you please take a look at this run failure? Keep me posted on what you find, thanks! 
https://www.openfn.org/projects/miraclefeet/runs/06218895-274b-7385-90aa-81eae0959080

cc @lakhassane
