### ISSUE TITLE
Do not upload Salesforce data if state contains test CommCare username

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#128]
## Background, context, and business value
See issue #25 for background. 
We have a new job that has multiple operations/steps... so we can't simply replicate what was implemented for issue #25, where the jobs only have 1 operation. 

## The specific request, in as few words as possible
For this new `upsert_brace_inventory.js`  job, we want to run NO steps, if 
`state.data.form.calcs.case_properties.clinic_code contains any `discardedClinics` (see the list of clinics I added to the job on L3). 
https://github.com/OpenFn/Miracle-Feet/blob/6beb2adc7b5e26b6c97ee66b002b143ad5ecd190/upsert_brace_inventory.js#L2-L82

If `state.data.form.calcs.case_properties.clinic_code` = ANY one of these discardedClinics, stop the job. Do not run any of the following steps... so no `query` or `upsert` functions should execute. 

## state
configuration: 
See LP/ ask Mamadou for `MiracleFeet SMS Sandbox Salesforce`

data: 
https://www.openfn.org/projects/miraclefeet/messages/0620e078-8e4a-770d-85ad-8370af788d0f

## expression
https://github.com/OpenFn/Miracle-Feet/blob/master/upsert_brace_inventory.js

## adaptor
`language-salesforce` --> Use FakeAdaptor for testing

## output 
Do not execute any actions in Salesforce if state contains a test CommCare clinic. Otherwise, proceed as normal (nothing should change about the job execution). 

Re-try this run failure after making the changes (this should now be logged as a successful run, but with no actions executed in Salesforce): https://www.openfn.org/projects/miraclefeet/runs/0620e675-4af6-7cb6-a9a5-4bda58c3e718

**Comment by grayey** [comment]
@aleksa-krolls , this has been done.

**Comment by aleksa-krolls** [comment]
thanks, @grayey. closing this
