### ISSUE TITLE
Skip scheduling `visitAfter` reminder if `sendAt` date is more than 6 months ahead

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#134]
## Background, context, and business value

We schedule [visitAfter](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=379768061&range=116:117) reminder SMS-s to be sent 5 days after a contact's `nextVisitDate`. Sometimes these dates are far ahead in the future. However the Infobip API doesn't let us schedule SMSs more than 6 months ahead.

## The specific request, in as few words as possible
Let's check if the [sendAtDate](https://github.com/OpenFn/Miracle-Feet/blob/97e9d9520a07a2717395ee2a36aa77a36e879ecc/schedule_smsV2.js#L422-L424) of the `visitAfter` reminder is more than 6 months ahead. If it is, `break` the loop and not send that alert.

## state.json
State for testing: https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/nextVisitDateTest.json
Config: see `Infobip Portal (MiracleFeet)` in `LP`

## adaptor
`language-https`

## expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_smsV2.js

Ping @ritazagoni for any questions or testing.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @grayey thanks for the work here! Can I request that when you move something to `Review` that you leave a quick comment? 

This way @ritazagoni is notified to check things out and doesn't have to check the backlog every day and every hour to see :)

**Comment by taylordowns2000** [comment]
Yes @aleksa-krolls , good call! @ritazagoni and I actually discussed the handover on Slack yesterday and she moved onto testing, but because I didn't write anything on the Github issue here you didn't have that visibility... apologies there. We can make sure there's always a note (at least referencing an ongoing Slack thread) when shifting to Review.

@grayey , please note this well!

**Comment by aleksa-krolls** [comment]
@ritazagoni friendly reminder to close this issue once changes are tested.
