### ISSUE TITLE
Update job to delete scheduled messages from Infobip if Treatment is Suspended or Completed

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#30]
## Background, context, and business value

Apart from scheduling and rescheduling messages as described in issue #27, job `schedule_sms.js` also needs to delete scheduled messages in Infobip when certain triggers are met.

For example: [wip...]

## The specific request, in as few words as possible

Job `schedule_sms.js` needs to delete previously scheduled messages from Infobip when triggers `sms_opt_in = 'yes' AND send_sms = 'on' AND treatment = "complete"` or `sms_opt_in = 'yes' AND send_sms = 'on' AND treatment = "suspended"` are met.

## state.json

See these two example payloads from CommCare.

https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json
https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/newVisit_ReminderMessage.json
For Infobip login see LP Infobip Portal (MiracleFeet).

## adaptor

`language-http`

## expression.js

Update job `schedule_sms.js` https://github.com/OpenFn/Miracle-Feet/tree/schedule_sms

## output.json

Every time a case is updated with triggers corresponding to `Treatment Completed` or `Treatment Suspended` (see exact triggers below), all previously scheduled messages for the case need to be deleted from Infobip. New messages need to be scheduled based on the triggers according to existing specifications in https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=542770724

`Treatment Suspended`

"send_sms": "on"
"sms_opt_in": "yes"
"treatment": "suspended"

For the above trigger, all previously scheduled messages for the case need to be deleted and messages for alert 19 need to be scheduled according to Schedule start date, Schedule date, Schedule time.

`Treatment Completed`

"send_sms": "on"
"sms_opt_in": "yes"
"treatment": "completed"

For the above trigger, all previously scheduled messages for the case need to be deleted and messages for alert 13 need to be scheduled according to Schedule start date, Schedule date, Schedule time.

The exact messages that will be sent out in this scenario are here.
### side effects

1. Delete previously scheduled messages for case.
2. Schedule new messages for case based on trigger.

**Comment by aleksa-krolls** [comment]
@ritazagoni does issue #35 replace this? If yes, can we close this one?

**Comment by ritazagoni** [comment]
#35 is the new issue for the same requirement, closing this one.

**Comment by ritazagoni** [comment]
hey @lakhassane  in this run https://www.openfn.org/projects/pdbznd/runs/r7x49m44 on message we want to cancel scheduled messages as treatment is set to `suspended`. However we are trying to cancel some of them twice (from `line 27`:
```
alerts to disable [
  { key: '03 - Casting Introduction', bulkPrefix: 'casting_intro-' },
  { key: '04 - Casting Campaign', bulkPrefix: 'casting_intro-' },
  {
    key: '14 - Reminder: 2 days before visit',
    bulkPrefix: 'visitBefore-'
  },
  {
    key: '15 - Reminder: 1 day after missed visit',
    bulkPrefix: 'visitAfter-'
  },
  { key: '03 - Casting Introduction', bulkPrefix: 'casting_intro-' },
  { key: '04 - Casting Campaign', bulkPrefix: 'casting_intro-' }
] 
```

And I think that's why the request to Infobip  fails  (`line 210`) as we are trying to cancel a message twice:
```
{
  "statusCode": 409,
  "body": {
    "requestError": {
      "serviceException": {
        "messageId": "CONFLICT",
        "text": "Bulk with id casting_intro-12-12c36dd7-9a97-44cb-bfb6-83ce86d5840d cannot be set to status CANCELED"
      }
    }
  },
```

**Comment by lakhassane** [comment]
@ritazagoni yes there were a logic error that add the same alerts twice in the array. You can re-test and let me know.
