### ISSUE TITLE
Update: Jobs to schedule SMSs on Infobip based on updates in CommCare

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#32]
## Background, context, and business value

See issue #27 for the original specs. 

**Changes**

1. New versions of state for mapping and testing: [sample message 1](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json), [sample message 2](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/newVisit_ReminderMessage.json)

2. Updated the mappings referenced in the SMS template, bulkId, and phone number from and destinations field - see (1)  [Output mapping](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=220153434) and (2) updated columns D & M-X in the Master Mapping sheet

3. Clarified the logic for when SMS alerts should be triggered (see [this diagram](https://lucid.app/lucidchart/invitations/accept/eace5d3b-1dce-4e58-9979-f2a26cf2d00b))

The scope of the changed specifications is `Alerts 1-16` and `Alert 19`.
The remaining alerts will be handled in a separate issue.

## The specific request, in as few words as possible

Create 1 job that executes the following steps (see Actions section for more detail)...
1. CommCare will send OpenFn a notification with triggering sms information
2. OpenFn should set a `bulkId` for all relevant message types (see mapping specs for instructions)
3. Then use these `bulkId`-s to query the Infobip API to fetch which messages have already been scheduled via `GET '/sms/1/bulks'`. 
4. Using `bulkId` to match and compare the response to step #3 to determine which SMSs already exist in Infobip...
5a. If SMS does _not_ exist in Infobip, schedule new SMS via `POST '/sms/2/text/advanced'`
5b. If SMS does exist in Infobip, reschedule the SMS using `bulkId`  via `PUT '/sms/1/bulks'`

Note that we're replicating an upsert pattern here where we first check for existing SMSs, and then schedule or reschedule depending on whether that SMS already exists. 

**Design docs:** 
1. See [data flow](https://lucid.app/lucidchart/9454d9ca-7c35-482d-b9e9-0e41284d1281/edit?beaconFlowId=18E49BC433DBA277&page=0_0#?folder_id=home&browser=icon)
2. See [mapping specifications](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=472550871)
3. See list of [alerts and corresponding triggers](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774)
4. See [message content in different languages](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774)
5. See this [sample job](https://gist.github.com/aleksa-krolls/6af43936d55d68383d5c0dce27d84d64) that defines message templates in different languages and posts an HTTP request to send a message through Infobip with a template selected based on properties in state. It also assigns a bulkId to each message. Issue will be updated with exactly how to construct the bulkId.
6. Use API docs: 
https://www.infobip.com/docs/api#programmable-communications/sms/send-sms-message

### Trigger
This job will run when `"sms_opt_in": "yes"` --> the job will then need to evaluate different CommCare case properties to determine which SMS type(s) should be scheduled. See the `Triggering Criteria` column in the [Alerts mapping specs](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=542770724). 

This job may trigger 1 or multiple SMSs depending on what properties are included in `state`. The case `language_code` will then determine which language these SMSs will be sent. 

### Actions
The job should automate the following actions:
1. Construct unique bulkId for every relevant message for a case based on properties in `state`.
2. Query scheduled SMSs for a case on Infobip by `bulkId`.
API docs: https://www.infobip.com/docs/api#programmable-communications/sms/get-scheduled-sms-messages
3. Determine which message(s) to schedule based on `bulkId` and `language_code` based on whether message already have been scheduled in Infobip (see step 2).
4. If message hasn't been scheduled yet, schedule SMS(s) on Infobip.
API docs: https://www.infobip.com/docs/api#programmable-communications/sms/send-sms-message
5. If message has been already scheduled, reschedule the message for the same date and time
API docs: https://www.infobip.com/docs/api#programmable-communications/sms/reschedule-sms-messages

You can see message logs on Infobip at https://portal.infobip.com/analyze/logs.

## state.json
See these example payloads from CommCare.
Examples 1 and 2 have the same JSON structure and can be handled by the same job:
1. https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json
2. https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/newVisit_ReminderMessage.json

For Infobip login see LP `Infobip Portal (MiracleFeet)`. 

## adaptor
`language-http`

## expression.js
Create 1 new job `scheduleMessages.js`

## output.json
Every time a case is created or updated in CommCare, determine which message(s) need to be scheduled. Schedule new messages and reschedule existing messages.

For the sample state for [patient registration](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json) we have the following potential triggers in `state` (see potential triggers [here](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=2026279226):

`"send_sms": "on"`
`"sms_opt_in": "yes"`
`sms_opt_in_educational = 'yes'`
`"treatment": "bracing_night"`

Based on [alerts and their triggers](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774), messages for `alerts` `8`, `9`, `10`, `11` and `12` need to be scheduled according to [Schedule Start Date (SSD), Days from SSD, Clock Time, Min From SSD](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=F1:I1).

Also from `state`:
`"language_code": ""`
the language of the messages has to be the default English.

The exact messages that will be sent out in this scenario are [here](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=N48:N106).

## Toggl
https://track.toggl.com/3335160/projects/165487722/team

**Comment by aleksa-krolls** [comment]
@lakhassane Please keep me posted on progress via Slack later today and if helpful to do a quick call this afternoon. Remember Rita is offline today, thanks!

**Comment by ritazagoni** [comment]
@lakhassane On a first test https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js had failed runs:
1. run: https://www.openfn.org/projects/419/runs/10878731 failed on message https://www.openfn.org/projects/419/messages/10393869.
2. run: https://www.openfn.org/projects/419/runs/10878936 failed on message https://www.openfn.org/projects/419/messages/10393864

**Comment by ritazagoni** [comment]
@lakhassane A few more corrections for https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js, run https://openfn.org/projects/419/runs/10888852 on message https://openfn.org/projects/419/messages/10393869

1. SMS #2 (`bulkId casting_intro-2-606562d6-c972-4f17-ad9c-7451ca920a1c` and  #3 (`bulkId casting_intro-3-606562d6-c972-4f17-ad9c-7451ca920a1c` are all scheduled to `now()`, should be https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=5fd69d22#gid=262234774&range=G7:I8

2. Job is looking for `next_visit_date` at the wrong place (`calcs.general`) (`Line 148` `(node:56331) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'next_visit_date' of 'calcs.general' as it is undefined.`), should be: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=5fd69d22#gid=262234774&range=F108:F112

**Comment by ritazagoni** [comment]
@lakhassane Error in run https://openfn.org/projects/419/runs/10901496 on message https://openfn.org/projects/419/messages/10424440: The run hasn't scheduled any alerts even though `state` fulfilled triggers in https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=5fd69d22#gid=262234774&range=D23 and should have scheduled https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=5fd69d22#gid=262234774&range=N23.

**Comment by ritazagoni** [comment]
@lakhassane The job is not setting next visit reminders. Example run https://openfn.org/projects/419/runs/10902057 on message https://openfn.org/projects/419/messages/10425100. In `state` `form.calcs.next_visit_date.next_visit_date` is filled as per https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=5fd69d22#gid=262234774&range=112:112

**Comment by ritazagoni** [comment]
@lakhassane run https://openfn.org/projects/419/runs/10902750 on message https://openfn.org/projects/419/messages/10425945 threw an error: `line 647`: `UnhandledPromiseRejectionWarning: Unhandled promise rejection.`
Could you please check?

**Comment by aleksa-krolls** [comment]
@ritazagoni What is the status of this issue? I see the new issues #33 #34 and #35 for additional requests. Is everything else working so far? Can we close this one if so?

**Comment by ritazagoni** [comment]
In run https://www.openfn.org/projects/pdbznd/runs/r5eg3mpg on message https://www.openfn.org/projects/pdbznd/messages/mpqdqnb5
we’re setting the `bulkId` `bracing_intro-2-c70bc68a-2e94-4072-b06c-08143013b33f` to be sent at 
2021-03-12T05:33:12.055Z

Then in run https://www.openfn.org/projects/pdbznd/runs/rk5b86m3 on message https://www.openfn.org/projects/pdbznd/messages/m58qdmw8 a week later let we don't find it already scheduled and setting again the same `bracing_intro-2-c70bc68a-2e94-4072-b06c-08143013b33f`
To be sent at 2021-03-17T06:16:14.263Z

**Comment by lakhassane** [comment]
@ritazagoni could this error be due to the fact that the date is passed? Can we get an sms once it is already sent?

**Comment by ritazagoni** [comment]
@aleksa-krolls This is the duplicate issue referenced in https://docs.google.com/document/d/1gY--jnX6e_sXSCOnFOJ3sVnrWhE-i_pd64reQSCrNwc/edit#. Next step would be to check whether we can find past scheduled and sent messages on Infobip API when querying for scheduled messages. It might be the case that we can't see past messages so we schedule them again.

**Comment by ritazagoni** [comment]
New separate issue for querying/modifying sent SMS-s in Infobip: https://github.com/OpenFn/Miracle-Feet/issues/55
