### ISSUE TITLE
Schedule alert for missed appointments

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#34]
## Background, context, and business value

When a patient has not visited the clinic on their appointment date, we want to schedule an SMS alert to be sent 1 day after their missed appointment date. See alert type [#18](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=113:114) in the `Master Mapping Table`. 

Every time a message arrives from CommCare, check for scheduled missed reminders using `last_visit_date` and reschedule them for  the new `next_visit_date`. If they don't exist, schedule a new reminder for `next_visit_date`.

## The specific request, in as few words as possible

Modify existing `schedule_sms.js` job to execute 1 other logic flow to schedule alert #18 for `Missed Appointments`. See [data flow diagram on Alerts tab](https://lucid.app/lucidchart/9454d9ca-7c35-482d-b9e9-0e41284d1281/edit?page=0_0#). 

**1.** Check if state to determine the values for the `last_visit_date` or `next_visit_date` properties. 
- For `last_visit_date`, check `form.calcs.save.last_visit_date` || `form.calcs.original_next_visit_date`
- For `next_visit_date`, check `form.calcs.general.next_visit_date` || `form.calcs.next_visit_date.next_visit_date` 

**2.** If any `last_visit_date` property exists, search for existing SMSs with the bulkIds: 
`visitAfter1-{form.case.@case_id}-{last_visit_date}`
`visitAfter2-{form.case.@case_id}-{last_visit_date}`

**2.1.** If matching SMSs are found, delete these SMSs. Then proceed to step 3 to schedule new ones. 
**2.2.** If no matching SMSs found in step `2` OR if `last_visit_date` property not defined in state, proceed to step `3`. 

**3.** Schedule 2 new SMS reminders for Alert Type [#18](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=113:114)  with the following bulkIds: 
`visitAfter1-{form.case.@case_id}-{next_visit_date}` 
`visitAfter2-{form.case.@case_id}-{next_visit_date}` 
See [mapping specs](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=5fd69d22#gid=262234774) for other mappings. 

## state.json

See these three example payloads from CommCare: 
1. `Log Visit Details` https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/newVisit_ReminderMessage.json
2. `Future Appointments` https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/future_appointments.json
3. `Register New Patient` https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json

## adaptor
`language-http`

## expression.js

Update job `schedule_sms.js` https://github.com/OpenFn/Miracle-Feet/tree/schedule_sms 

## output.json
Example: 
If a patient has a `next_visit_date` set for `19-12-2020` we need to schedule [Alert #18](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=5fd69d22#gid=262234774&range=113:114)  to be sent out on `20-12-2020`. 
If their visit date has changed and they have an 'original_next_visit_date' for '19-12-2020' and a 'next_visit_date` for `23-12-2020`, we need to reschedule the reminder previously set for `original_next_visit_date` to match `next_visit_date`.

**Comment by aleksa-krolls** [comment]
@ritazagoni Can you please recommend what should be the `trigger` in prod across these 3 versions of state? This will influence whether we request 1 or multiple jobs. FYI, currently for [Schedule SMS job](https://www.openfn.org/projects/pdbznd/jobs/jypnkm) we use `{"form":{"calcs":{"sms":{"sms_opt_in":"yes"}}}}`. 

Then, how does this fit into the data flow diagram you created for the other alerts scheduling? Does this impact any of the other alerts, or is this a completely different flow? I think it would be helpful to spend ~15 min to create a diagram showing the scheduling flow for this request, because I _think_ the scheduling logic is the same across all 3 versions of state, yes? (Only the mappings change?)

**Comment by aleksa-krolls** [comment]
@lakhassane one more MF issue to take up today or tomorrow morning. There will be 1 more tomorrow AM as well. Let me and @ritazagoni know if any questions before you get started.

**Comment by ritazagoni** [comment]
hey @lakhassane Run https://www.openfn.org/projects/pdbznd/runs/rn56r7bd on message https://www.openfn.org/projects/pdbznd/messages/mwb8v48a (Register New Patient form) didn't schedule an alert, please check!

**Comment by ritazagoni** [comment]
hey @lakhassane 
in this run https://www.openfn.org/projects/pdbznd/runs/r6g67bxw on message https://www.openfn.org/projects/pdbznd/messages/mqp4pvjz we are setting the `visitAfter-1` message `bulkId` as `visitAfter-1-12c36dd7-9a97-44cb-bfb6-83ce86d5840d-undefined` instead of `visitAfter-1-12c36dd7-9a97-44cb-bfb6-83ce86d5840d-2021-03-12` (based on `form.calcs.general.next_visit_date`, according to [mapping spec](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=113:113))
Could you please check why that's happening?

**Comment by ritazagoni** [comment]
@lakhassane related error: in run https://www.openfn.org/projects/pdbznd/runs/ryaxpzxw for the same patient, on message https://www.openfn.org/projects/pdbznd/messages/mpqdqnzn we are running into an error from Infobip: not finding the bulkId `bulkId=visitAfter-2-12c36dd7-9a97-44cb-bfb6-83ce86d5840d-2021-03-17` where `2021-03-17` is the newly set `next_visit_date`. 

I've added docs for this scheduling logic to the [Readme](https://github.com/OpenFn/Miracle-Feet#notes-on-scheduling-logic)
Also ping me for any clarification or pair troubleshooting!

**Comment by lakhassane** [comment]
@ritazagoni For you first comment, the `undefined` is for `last_visit_date`actually. We first build the `bulkId` with that one and check to see if any sms exist. If none that's when we schedule a new sms with `next_visit_date` (you can see in the run that new `bulkId` is set correctly, line 72).

I don't see `last_visit_date` in the sample data, reason why we are having this `undefined`.

**Comment by lakhassane** [comment]
@ritazagoni for your second comment, I made the correction. You can try re-running that same sample data to check.

**Comment by ritazagoni** [comment]
This looks good, thanks @lakhassane .

There is also a duplication issue with the `visitAfter` messages, some messages are scheduled and sent twice. 

Looking at these two runs for the same case:
Run 1: https://www.openfn.org/projects/pdbznd/runs/rbgy84ba
```
alerts to send [
  { key: '03 - Casting Introduction', bulkPrefix: 'casting_intro-' },
  { key: '04 - Casting Campaign', bulkPrefix: 'casting_intro-' },
  {
    key: '15 - Reminder: 1 day after missed visit',
    bulkPrefix: 'visitAfter-'
  },
  {
    key: '15 - Reminder: 1 day after missed visit',
    bulkPrefix: 'visitAfter-'
  }
]
```

We’re setting these `bulkId`-s twice:
`visitAfter-1-1100a33e-20ad-4cc5-911c-3631a5f2d2bf-2021-03-25`
`visitAfter-2-1100a33e-20ad-4cc5-911c-3631a5f2d2bf-2021-03-25`

Run 2: https://www.openfn.org/projects/pdbznd/runs/rd7zj4pe

We’re setting these `bulkId`-s twice:
`visitAfter-1-1100a33e-20ad-4cc5-911c-3631a5f2d2bf-2021-03-18`
`visitAfter-2-1100a33e-20ad-4cc5-911c-3631a5f2d2bf-2021-03-18`

**Comment by lakhassane** [comment]
@ritazagoni I implemented this new logic. Let me know when testing for assistance.

**Comment by ritazagoni** [comment]
Thanks @lakhassane  Just tested: in run https://www.openfn.org/projects/pdbznd/runs/renw6jm3 on message https://www.openfn.org/projects/pdbznd/messages/mrbrn8k8 we are scheduling the `visitAfter` messages using the wrong bulkId which has `last_visit_date` (`visitAfter-2-8c9efe99-deb6-44c0-97c9-56296100b2d4-2021-06-10`). However the date we are scheduling the message for is correct: it's for `next_visit_date`. We should be using `next_visit_date` in the bulkId when scheduling: `visitAfter-2-8c9efe99-deb6-44c0-97c9-56296100b2d4-2021-06-21`.

**Comment by lakhassane** [comment]
ahh yeah I think it's normal @ritazagoni . I should add more log so it get more clear.
What happens is we check last_visit_date (point 2) and also next_visit_date (point 3). Let's schedule 10mn on Monday so I can walk you through the logic.

**Comment by lakhassane** [comment]
@ritazagoni I added the logs

**Comment by ritazagoni** [comment]
bulkId issue fixed see https://www.openfn.org/projects/pdbznd/runs/renw7xxd
