### ISSUE TITLE
Delete other scheduled treatment alerts if treatment changes

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#35]
## Background, context, and business value

As an extension of #32: Every patient is undergoing only one treatment any given time, but the treatment may change or is suspended/completed/stopped. 

In case the treatment changes, we don't want the patient to receive alerts related to their previous treatment. 

If the treatment is suspended, completed or stopped, we don't want the patient to receive any treatment alerts or future visit reminders or missed visit reminders.

## The specific request, in as few words as possible
There are 2 scenarios where we want to delete SMSs. See [data flow diagram](https://lucid.app/lucidchart/9454d9ca-7c35-482d-b9e9-0e41284d1281/edit?page=kw4X.3MwKY.U#).

**1.**  If a `Log Visit Details` form arrives that has the following properties (for sample data see https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/log_visit_details_original_treatment.json)

`form.calcs.sms.original_treatment = "casting" OR "tenotomy" OR "bracing_day" or "bracing_night" `
AND `form.calcs.sms.treatment = casting" OR "tenotomy" OR "bracing_day" or "bracing_night"`
EXAMPLE: `form.calcs.sms.original_treatment = "tenotomy"`

THEN
a. Delete all scheduled messages for treatment indicated in `form.calcs.sms.original_treatment`. In this example, delete message with `bulkId` `tenotomy-{form.case.case_id}`.

b.If  `form.calcs.sms.original_treatment = "bracing_day" or "bracing_night"` delete all scheduled messages for Alert 14, 15, 16 using the following `bulkId`-s: `not_wearing_brace-{form.case.case_id}`, `not_tolerating_brace-1-{form.case.case_id}`, `not_tolerating_brace-2-{form.case.case_id}`,  `not_accepting_brace-{form.case.case_id}`(https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=M108:M111)

**2.**  If a `Log Visit Details` form arrives that has the following properties (for sample data see https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/log_visit_details_original_treatment.json)
`form.calcs.sms.treatment = "complete" OR "suspended"`

OR if a `Stopped Treatment` form arrives that has the following properties (for sample data see https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/stopped_treatment.json)
`form.properties.close_reason != ""`

THEN 
Execute step `a` and `b` above AND ALSO

c. Delete all scheduled visit reminders (Alert 17) using `bulkId` = `visitBefore-form.case_id + form.calcs.next_visit_date.next_visit_date || form.properties.next_visit_date_formatted`  [see sheet](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=M112)

d. Delete all scheduled missed appointment reminders (Alert 18) using `bulkId` = `visitAfter1-form.case_id + form.calcs.next_visit_date.next_visit_date` and  `bulkId` = `visitAfter2-form.case_id + form.calcs.next_visit_date.next_visit_date || form.properties.next_visit_date_formatted` [see sheet](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=M113:M114) 

## state.json

`Log Visit Details` form: https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/log_visit_details_original_treatment.json
`Stopped Treatment` form: https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/stopped_treatment.json

## adaptor
`language-http`

## expression.js
Update job `schedule_sms.js`

## output.json

1. If a `Log Visit Details` form arrives that has the following properties:
`form.calcs.sms.treatment = "casting"`
`form.calcs.sms.original_treatment = "tenotomy"`
THEN delete scheduled message with `bulkId= tenotomy-{form.case.case_id}`

2. If a `Log Visit Details` form arrives that has the following properties:
`form.calcs.sms.treatment = "suspended"` OR `form.calcs.sms.treatment = "completed"`
`form.calcs.sms.original_treatment = "tenotomy"`
`form.calcs.next_visit_date.next_visit_date = 2021-02-04`
 
OR if a `Stopped Treatment` form arrives that has the following properties:
`form.properties.close_reason = "stopped_coming"`
`form.properties.next_visit_date_formatted = "04/02/21"`
`form.calcs.sms.original_treatment = "tenotomy"`

THEN  
a. Delete scheduled message with `bulkId= tenotomy-{form.case.case_id}` 
b. Delete scheduled messages with bulkId =  `visitBefore-{form.case_id}-2021-02-04`
c. Delete scheduled messages with bulkId =  `visitAfter1-{form.case_id}-2021-02-04`
d. Delete scheduled messages with bulkId =  `visitAfter2-{form.case_id}-2021-02-04`

**Comment by aleksa-krolls** [comment]
@ritazagoni Similar feedback as my comment on issue #34...
1. What should the trigger be on prod? (We'll need to consider if this is in the same job or a different one.)
2. Can you spend ~20 min on a new data flow diagram or extending the original one? 
3. In this issue, you have a handful of requests like `Delete all scheduled messages for Alert 14, 15, 16`... should we delete using `bulkId`? It might be nice to structure these specifications to show `IF x, y, z criteria is met, THEN delete SMSs with a, b, c bulk Ids` where you actually provide a list of bulk Ids (rather than having Mamadou try to figure out exactly which SMSs should be deleted).

**Comment by lakhassane** [comment]
@aleksa-krolls @ritazagoni I have 2 questions in this:
1. Could the path for `original_treatment` be rechecked. It is not in the given path as per the request.
2. In `1.b` should we delete alerts `14, 15, 16` even IF `brace_problems_type` is not in the payload (this assume that those alerts were scheduled). Or read the value from the payload and delete that one (it can be only `alert 14` for example or all 3)?

**Comment by ritazagoni** [comment]
@lakhassane 
1. We are updating the forms so that the path will be what's indicated in the issue. Please go by that even if you can't test with current state version of state.

**Comment by ritazagoni** [comment]
@lakhassane I ran into an error in this run https://www.openfn.org/projects/pdbznd/runs/rn56deky on message https://www.openfn.org/projects/pdbznd/messages/mrb8pzd6

**Comment by aleksa-krolls** [comment]
@lakhassane please update the job to handle scenarios where NO `original_treatment` is provided (see message here:  https://www.openfn.org/projects/pdbznd/messages/mrb8pzd6 ). In such scenarios, assume no treatment alerts need to be deleted... so you can skip this step and move onto the next step in the logic flow.

**Comment by ritazagoni** [comment]
@lakhassane I confirm to handle no `original_treatment` this way. Please let us know if this is implemented  

>  update the job to handle scenarios where NO `original_treatment` is provided (see message here: https://www.openfn.org/projects/pdbznd/messages/mrb8pzd6 ). In such scenarios, assume no treatment alerts need to be deleted... so you can skip this step and move onto the next step in the logic flow.

**Comment by ritazagoni** [comment]
@lakhassane state for `Mark Stopped Treatment` has changed, please see new sample [here](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/newStoppedTreatment.json).

For scenario 2 in issue, please look for `form.close_reason != ""` instead of `form.properties.close_reason != ""`

**Comment by aleksa-krolls** [comment]
@ritazagoni can you close any MF issues that are working now? Thanks!

**Comment by ritazagoni** [comment]
hey @lakhassane there was an other failed run: https://www.openfn.org/projects/pdbznd/runs/rj5kk98n on message https://www.openfn.org/projects/pdbznd/messages/mqpqvqw4 could you check?

**Comment by ritazagoni** [comment]
hey @lakhassane  we have a few new failed runs with schedule_sms.js from the client's testing. this is one type: https://www.openfn.org/projects/pdbznd/runs/rrkawd85 on message https://www.openfn.org/projects/pdbznd/messages/mk5nej8r. could you check?

**Comment by ritazagoni** [comment]
@lakhassane a different error here: https://www.openfn.org/projects/pdbznd/runs/r3xay7pm on https://www.openfn.org/projects/pdbznd/messages/mdba4vg5

**Comment by aleksa-krolls** [comment]
@ritazagoni if nothing to be worked on now, I'm moving back to `Review/QA` until we look into this.

**Comment by aleksa-krolls** [comment]
@lakhassane We're seeing some failures that I think are related to this logic handling. `TypeError [Error]: Cannot read property 'map' of undefined`. 
https://www.openfn.org/projects/pdbznd/runs/rzdr7n5n
https://www.openfn.org/projects/pdbznd/runs/rj5kgnx5
https://www.openfn.org/projects/pdbznd/runs/rk57myj7
https://www.openfn.org/projects/pdbznd/runs/rrka4rp5
https://www.openfn.org/projects/pdbznd/runs/ryajm7gz

Please make sure all 5 runs succeed.

**Comment by lakhassane** [comment]
All runs are successful:
https://www.openfn.org/projects/pdbznd/runs/rwamern4
https://www.openfn.org/projects/pdbznd/runs/rzdrexzg
https://www.openfn.org/projects/pdbznd/runs/rn5974bn
https://www.openfn.org/projects/pdbznd/runs/rx8weaky
https://www.openfn.org/projects/pdbznd/runs/rzdrexzd

**Comment by aleksa-krolls** [comment]
@lakhassane Another failure where `"language_code": "es"`... can we please convert all `language_code` values to lowercase before evaluating so that either `en` or `EN` will work? Thanks!
https://www.openfn.org/projects/pdbznd/messages/me66va6q

**Comment by ritazagoni** [comment]
hey @lakhassane found a new failed run https://www.openfn.org/projects/pdbznd/runs/raa387m3 on message https://www.openfn.org/projects/pdbznd/messages/m8qqv48b

**Comment by ritazagoni** [comment]
hey @lakhassane we ran into an error with canceling messages: failed run https://www.openfn.org/projects/pdbznd/runs/r5eamapm on message https://www.openfn.org/projects/pdbznd/messages/mk55dg68

**Comment by lakhassane** [comment]
@ritazagoni the error has to do with the sms you are trying to cancel. That sms was already sent so you cannot cancel it.
<img width="256" alt="Screen Shot 2021-02-01 at 09 41 41" src="https://user-images.githubusercontent.com/8411231/106441227-b4109600-6471-11eb-886c-86f0ae5be4f6.png">

**Comment by ritazagoni** [comment]
@lakhassane I see. The user scenario here is that after some SMS-s have been scheduled and sent the patient opts out of further messaging. Is there a way we can handle this by checking if a `bulk-id` has already been sent or if SMS that needs to be canceled was supposed to be scheduled for a past date?

**Comment by aleksa-krolls** [comment]
@ritazagoni do we have any ready-to-go SMS feedback/ can we close this issue?
