### ISSUE TITLE
Only run schedule_sms.js job flow if username contains 'test'

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#38]
## Background, context, and business value

As the client is testing SMS scheduling, we want to check first in `schedule_sms.js` if in the forms `metadata.username` is a test account. We only want to run the entire job flow is it IS a test account and prevent scheduling SMSs for real clients. We will remove this logic before go-live. 

## Request
Update `schedule_sms.js` so that it FIRST checks for the below condition and only executes any further automation step IF :
`state.data.metadata.username` CONTAINS `'test'` OR `'practica'`

IF NOT... stop flow and do not run job. 

## state.json

[Sample form](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json)

## adaptor

`language-http`

## expression.js

Update `schdule_sms.js`

## output.json

Job only executes any steps if initial check on `metadata.username` passes.

**Comment by aleksa-krolls** [comment]
We're finding additional run failures, but not sure if it's related to this fix. See Rita's slack and below: 
https://www.openfn.org/projects/pdbznd/runs/rrkawd85 on message https://www.openfn.org/projects/pdbznd/messages/mk5nej8r

**Comment by aleksa-krolls** [comment]
@ritazagoni Please close out any complete MF issues. We can always reopen if something pops up.
