### ISSUE TITLE
Adjust SMS schedule time based on time zone from state

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#42]
## Background, context, and business value

When scheduling SMS messages, we need to schedule them taking into account the recipient's time zone.

## The specific request, in as few words as possible

Check `form.calcs.sms.time_zone` in `state`. Adjust scheduling time by appending `time difference` for that time zone based on the time zone/time difference mapping [here](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=774472213). 

Format for adjusting schedule time: if current schedule time is `2021-02-01T07:47:45.777` and `form.calcs.sms.time_zone` is 
[Africa/Kinshasa](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=774472213&range=18:18) with a time difference of `+01:00` then time zone-adjusted schedule time is `2021-02-01T07:47:45.777+0100`

## state.json

[Sample form](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/log_visit_details_original_treatment.json
)
## adaptor

`language-http`

## expression.js

Update job `schedule_sms.js`

### output.json

SMS-s are scheduled with time difference added to scheduling time.

**Comment by lakhassane** [comment]
Hey @ritazagoni @aleksa-krolls why this line in here `if current schedule time is 2021-02-01T07:47:45.777`.
In state schedule date is in this format: `"next_visit_date": "2020-12-24"`.
Should I still add the timezone. I guess yes, but I just want to confirm that line above is not constraining anything I'm not aware of.

**Comment by ritazagoni** [comment]
hey @lakhassane We need to add time zone to the specific time we are scheduling the message for in the job. Currently the format we're using for `sendAt` is ` sendAt: '2021-01-13T09:10:00.000Z'` which is set in `schedule_sms.js` here: https://github.com/OpenFn/Miracle-Feet/blob/97012e72b3c0b5a5db5208a855bf6e434781432c/schedule_sms.js#L535-L552

We need to add the time zone difference to that timestamp. Does that make sense?

**Comment by ritazagoni** [comment]
@lakhassane got `Invalid time value` in run https://www.openfn.org/projects/pdbznd/runs/rn5ae3ka on message https://www.openfn.org/projects/pdbznd/messages/mgkkke7v

**Comment by ritazagoni** [comment]
@lakhassane Looks like we are adding 1 second instead of [1 hour](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=774472213&range=19:19)
in this run https://www.openfn.org/projects/pdbznd/runs/r3xy7kze on message https://www.openfn.org/projects/pdbznd/messages/mwb83aja
See lines `39-44` and [required schedule time (10am)](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774&range=9:9)
```
Sending message: {
  from: 'TSCFFOOT',
  destinations: [ { to: '23411111111111' } ],
  text: 'Hi mama. Make sure that new plaster casts are dry before allowing display to play so pressure from standing or crawling does not affect their shape.',
  sendAt: '2021-02-25T10:00:06.518Z'
}

```
