### ISSUE TITLE
TypeError [Error]: combine(...)(...)

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#43]
## Describe the bug
See the run failure here: https://www.openfn.org/projects/pdbznd/runs/rrkw9ywe

Recent success where LP and Core version look the same:
https://openfn.org/projects/pdbznd/runs/r5ezymjw

## To Reproduce
Feel free to re-run the job against this Message in prod: https://www.openfn.org/projects/pdbznd/messages/mn5kgdj7

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/add_new_visit__UPDATED.js
https://www.openfn.org/projects/pdbznd/jobs/jv8m7n

### state.json
See LP for `MiracleFeet Salesforce Production`

## Expected behavior
This job has been working fine and have only after @lakhassane push issue seen this pop up... wondering if it's somehow related... but not sure, could be something separate!

**Comment by lakhassane** [comment]
@aleksa-krolls I re-run a failed run for `add_new_visit` with success (https://openfn.org/projects/pdbznd/runs/r9war66j)
Would you check on your side and let me know.

**Comment by aleksa-krolls** [comment]
@lakhassane Thanks! passing now in my checks as well. What has changed to make it work?

**Comment by lakhassane** [comment]
Nothing has changed actually. Im still lost about what happened.
