### ISSUE TITLE
SMS alerts disabling: TypeError [Error]: Cannot read property '@case_id' of undefined

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#44]
## Background, context, and business value
`TypeError [Error]: Cannot read property '@case_id' of undefined`
See run failure: https://www.openfn.org/projects/pdbznd/runs/r9warkgr

Doesn't look like we're passing `case_id` properly... looks like SMS opt-in preferences came in as `no`, so we wan't to make sure no alerts go out. 

## state.json
Feel free to re-run this message on prod: https://www.openfn.org/projects/pdbznd/messages/mv7d574m

## adaptor

`language-http`

## expression.js

Update job `schedule_sms.js`

### output.json
No SMS alerts should be sent if sms preferences are no...
@ritazagoni here is where I think we need to revisit the logic. This is a new Registration, so SMS preferences were never set to true... there should be no alerts to disable. Let's discuss, but I think we need to refine the logic for disabling SMSs.... this Message should really trigger no runs.

**Comment by aleksa-krolls** [comment]
@ritazagoni hey this was something I saw pop up a few days ago and forgot to mention. Can you check this out sometime this week?

**Comment by ritazagoni** [comment]
I think there's 2 things going on here.

@lakhassane 
The source of the error is that `case_id` is now under 
```
"commcare_usercase": {
      "case": {
        "@case_id": "XXX",
      }
}
```
while it used to be 

```
"case": {
      "@case_id": "8dc1359b80634a418696fdcd1969b51b",
}
```

Please update `schedule_sms.js` so that it looks for `case_id`  on both the above paths.

@aleksa-krolls Let's see how it works once this is fixed and we can revisit the logic as needed.

**Comment by lakhassane** [comment]
@ritazagoni this has been corrected.
