### ISSUE TITLE
Visit run shows false success 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#45]
## Describe the bug
OpenFn logs a successful run, but this data is not showing up in Salesforce. 
https://www.openfn.org/projects/pdbznd/runs/r9w6k93a

I think this came up before already for this job, and I thought we had resolved this - see issue #41. This has definitely come up before in other Salesforce implementations. 

## To Reproduce
Feel free to re-run the job on prod, or use the related Message for state. 

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/add_new_visit__UPDATED.js

Please advise if changes need to be made across MF jobs: https://github.com/OpenFn/Miracle-Feet

### state.json
See LP for `MiracleFeet Salesforce Production`. 

## Expected behavior
Visits should be uploaded (and Salesforce will return an Id), or OpenFn should throw an error.

**Comment by lakhassane** [comment]
@aleksa-krolls this should be ok as soon as we clear out https://github.com/OpenFn/language-salesforce/pull/19 on `language-salesforce`as they are tighly related.

And yes we might need to update some of the jobs that are usinge `combine` currently.

**Comment by aleksa-krolls** [comment]
@lakhassane I want to make sure this issue is not lost, so I'm going to move this back to the backlog. Can you let me know when that pull request is merged and can you re-run the example I shared to verify it will fail? 
(I imagine this means there are several records not getting synced to Salesforce right now, and this worries me that there are data gaps growing with each day.)

**Comment by lakhassane** [comment]
@aleksa-krolls check here: https://www.openfn.org/projects/pdbznd/runs/r9w6pwmd

We are throwing an error like we are supposed to
