### ISSUE TITLE
HTTP job suceeds when 1 of the PUT requests Fail

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#50]
## Describe the bug
See example run that succeeds even though there are failures: https://www.openfn.org/projects/pdbznd/runs/rmkx7p7y
See related Slack thread: https://openfn.slack.com/archives/G2LJCFFDW/p1619689561008600

## To Reproduce
Feel free to re-run: https://www.openfn.org/projects/pdbznd/runs/rmkx7p7y

### expression.js
`schedule_sms.js`

### state.json
See LP for `Infobip Portal`

## Expected behavior
If any HTTP Request fails in a job, I expect OpenFn to throw an error to alert the administrator.

**Comment by lakhassane** [comment]
@aleksa-krolls corrections has been made so you are free to test. However, did not check the reason the scheduling is failing yet. Probably a conflit with the target resource (`409`).

**Comment by aleksa-krolls** [comment]
Thanks @lakhassane ... @ritazagoni will take a closer look at the failures.
