### ISSUE TITLE
Update SMS schedule times and text

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#51]
## Background, context, and business value

See issue #32 for latest version of original specs.

## The specific request, in as few words as possible

The time and text for some of the alerts has been updated, see version [Mapping Table -Edited v0305](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=606433e3#gid=179313688) of the mapping sheet. Please replace the `mapping` object in job `schedule_sms.js`

## state.json

See these example payloads from CommCare.
https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json
https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/newVisit_ReminderMessage.json

For Infobip login see LP Infobip Portal (MiracleFeet).

## adaptor

`language-http`

## expression.js

Update job `schedule_sms.js`

**Comment by aleksa-krolls** [comment]
@lakhassane did you mean to move these issues to `Review` or in `Backlog`? We're confused about that's done cc @ritazagoni
