### ISSUE TITLE
Disable alerts only if `original_treatment` !== `treatment`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#54]
## Request
Disable alerts only if `treatment` has changed. Sometimes the CommCare form state will show the property `original_treatment` even when `treatment` has not changed from the original: https://www.openfn.org/projects/pdbznd/messages/m58qdmw8

If treatment is the same, no need to disable alerts. 

## expression
Current expression looks like it disables the alert if the `original_treatment` key is present. 
https://github.com/OpenFn/Miracle-Feet/blob/c80f005589011703152980f22f773e823aa5a3ed/schedule_sms.js#L281-L284

## state
See LP for Infobip Portal

This message should disable alerts because the `treatment` differs from `original_treatment`
https://www.openfn.org/projects/pdbznd/messages/mpqdqnb5

This message should NOT disable alerts because `treatment` is the same as `original_treatment`
https://www.openfn.org/projects/pdbznd/messages/m58qdmw8

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Would you feel comfortable taking this on? I don't have time today to really walk you through it, so let's leave this for Mamadou if not very clear what the issue might be.

**Comment by lakhassane** [comment]
@aleksa-krolls I made the changes on this one.
Solving the issue with the language-code but not related.

**Comment by ritazagoni** [comment]
Fixed. [Run](https://www.openfn.org/projects/pdbznd/runs/rpdymjdg) doesn't disables messages for `original_treatment` which is the same as `treatment` in this [message](https://www.openfn.org/projects/pdbznd/messages/m58qdmw8).
