### ISSUE TITLE
Age_Months_First_Brace__c integer field outputting `0` value in Salesforce

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#56]
## Describe the bug
I'm stumped... I've modified the job `update_patient_UPDATED.js` to send an empty string `''` or blank value to Salesforce whenever CommCare doesn't send us age data (so CommCare will either send a `""` or `0`)...
https://github.com/OpenFn/Miracle-Feet/blob/96a9e4d1c3116a98a43b2f62af22ea2ae6899716/update_patient_UPDATED.js#L102-L107

I think I implemented this check correctly in the job, and the OpenFn run output looks fine (see L10)...
https://www.openfn.org/projects/pdbznd/runs/rbg6gb65

HOWEVER, in Salesforce the field keeps showing a `0` default value and not `''`...
![image](https://user-images.githubusercontent.com/16758106/118503494-59a2f900-b733-11eb-8649-ea89842e047b.png)
https://castapp.lightning.force.com/lightning/r/Contact/0033l00002o5nBNAAY/view

I've checked everywhere in Salesforce, and there is no automation or anything resetting this value to `0`... so something is going wrong when OpenFn is updating the record and trying to set a `''`. 
Can you please test and verify nothing wrong with our adaptor? Or perhaps there's another way to write this mapping? (If you're unsure how to resolve, I may submit a ticket to Salesforce to inquire why this is happening.)

## state
See LP for `MiracleFeet Salesforce production`
To test, please feel free to re-run this again on prod: https://www.openfn.org/projects/pdbznd/messages/m4p884rn
Again, strange that the OpenFn run looks fine... but the result is not what is expected in Salesforce. 

## expression
update_patient_UPDATED.js

**Comment by lakhassane** [comment]
corrected with last commit
