### ISSUE TITLE
RangeError [Error]: Invalid time value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#58]
## Describe the bug
See run failure here: https://openfn.org/projects/pdbznd/runs/rpdej959
Feel free to re-run on prod. Add handling for undefined values as needed. 

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/update_patient_UPDATED.js

### state.json
See LP for `MiracleFeet Salesforce Production`
https://openfn.org/projects/pdbznd/messages/me65nkvb

**Comment by lakhassane** [comment]
@aleksa-krolls the problem here is with the data I think.
Look how we have month = 24 in here
```     
"date_first_brace": "2021-24-03", 
```

**Comment by aleksa-krolls** [comment]
@lakhassane This is happening again, but the date format looks ok... any other ideas? https://openfn.org/projects/pdbznd/messages/mz733b7g
https://openfn.org/projects/pdbznd/messages/m95wwq5g

**Comment by lakhassane** [comment]
@aleksa-krolls there is still invalid format
`"date_tenotomy": "29-07-2020",`written like this instead of `year-month-day`
