### ISSUE TITLE
Report on # of Messages in a failed state 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#62]
## Background, context, and business value
The client is trying to setup systems to better monitor user activity in CommCare, OpenFn error rates, etc. From MF: 
```
I think it would be helpful for Amanda to have a way to see how many unresolved OpenFn 
errors there are in OpenFn on the CAST Admin Dashboard in Salesforce. This way 
could know when to talk to Sele - if the errors are piling up. Can you think of any 
good way for us to bring this data in?
```

## The specific request, in as few words as possible
Two things..
1. Metabase report on # of Messages in a failed state (grouped by receipt `inserted_at` date). To clean up the numbers in this report, and re-label the columns `0` and `1` to be `success` and `failure` so that non-OpenFn admins can understand this report. 
https://analytics.openfn.org/question/332

2. Then, would it be feasible to scrape this report and upload the run stats to Salesforce? (We don't need to implement this yet, but I want to understand if this option is even on the table if they wanted to get these Metabase results into Salesforce so they can look at 1 dashboard.)

**Comment by aleksa-krolls** [comment]
@taylordowns2000 I added what we discussed this morning to the backlog!

**Comment by taylordowns2000** [comment]
Wanted to get this documented here:

1. https://analytics.openfn.org/question/293 - this is now working. it's got the same filters as before and shows 58 rows
2. and this exlcudes `%uplicate%` and shows 28: https://analytics.openfn.org/question/337 

Something like it would certainly be possible—would we want to get hard numbers and then upload those numbers to a custom object with integer fields? What would it look like on the SF side in terms of objects/fields @aleksa-krolls ? This would help determine how we'd structure the report and the scraper. I'd almost prefer to have this automatically emailed each day/week and then use some sort of email-openfninbox-saleforce flow.
