### ISSUE TITLE
`bracing_day` SMS-s not scheduled

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#64]
## Describe the bug
In run https://www.openfn.org/projects/pdbznd/runs/rpdymjdg on the incoming message https://www.openfn.org/projects/pdbznd/messages/m58qdmw8  properties:
```
sms": {
        "original_treatment": "bracing_day",
        "send_sms": "on",
        "sms_language": "English",
        "sms_opt_in": "yes",
        "sms_opt_in_educational": "yes",
        "time_zone": "Africa/Lagos",
        "treatment": "bracing_day"
      },
```
and
```
"brace": {
      "brace_problems": {
        "brace_problems_type": "child_not_tolerating"
      },
```
we should have scheduled both `12 - Not Tolerating Brace`, `06 - Bracing Introduction` and `07 - Bracing All Day Campaign`. However, we did not schedule  `06 - Bracing Introduction` and `07 - Bracing All Day Campaign`.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/pdbznd/runs/rpdymjdg

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json
See `LP` for Infobip credentials.

## Expected behavior
In addition to the SMS-s scheduled, we also need to schedul `06 - Bracing Introduction` and `07 - Bracing All Day Campaign`.

## To test/resolve
1. After the desired output is working locally (from the CLI), please push commits to master.
2. Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pdbznd/runs/rpdymjdg) and confirming success.

**Comment by lakhassane** [comment]
Hey @ritazagoni I think it's quite normal.
The condition to send those red alerts (`bracing_XXX`) was that `original_treatment !== treatment` which is not the case in this form.

Check the section **Request** in those specs where it is explained: https://github.com/OpenFn/Miracle-Feet/issues/53

**Comment by ritazagoni** [comment]
thanks @lakhassane !
