### ISSUE TITLE
If `next_visit_date` is missing or empty, don't schedule visit reminders

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#67]
## Background, context, and business value

Currently we are trying to schedule visit reminders ([alert #17 and #18](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=606433e3&pli=1#gid=262234774&range=112:114)), (see also [data flow diagram](https://lucid.app/lucidchart/9454d9ca-7c35-482d-b9e9-0e41284d1281/edit?page=PMQTYrV0-q.h#)) even if `next_visit_date` is missing. 

Possible `next_visit_date` paths in `state`:
`form.calcs.general.next_visit_date`
`form.calcs.next_visit_date.next_visit_date`

Let us not schedule alerts #17 and #18 if `next_visit_date` is missing or empty.

As a result of the change, re-trying these runs should succeed without trying to schedule visit reminders: 
https://www.openfn.org/projects/pdbznd/runs/raa8ezme
https://www.openfn.org/projects/pdbznd/runs/rzdpewbg

## state.json

See `LP` for `Infobip` portal

## expression.js

Please update job https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

**Comment by ritazagoni** [comment]
Both runs still fail with `Invalid time value` https://www.openfn.org/projects/pdbznd/runs/rg5gb4x8 and https://www.openfn.org/projects/pdbznd/runs/rn5nm9px

**Comment by taylordowns2000** [comment]
See commit above: I suppose the question is still why we're picking that particular alert if the logic below is the desired business logic but there's no date in there.
```
=======================================
For 15 - Reminder: 1 day after missed visit, we're looking in form.calcs.next_visit_date.next_visit_date and finding 
RangeError [Error]: Invalid time value
    at Date.toISOString (<anonymous>)
```

**Comment by taylordowns2000** [comment]
@ritazagoni , did some more digging: the mapping rules for alert 15 dictate that you can only search in `"Schedule Start Date (SSD)":"form.calcs.general.next_visit_date || form.calcs.next_visit_date.next_visit_date"` for next visit date, however the submission highlighted here has `next_visit_date` in the `calcs.save.next_visit_date` path.

I've added some more logs to highlight this. Seems like an update to the mapping or a change to how we decide when to send SMS required?

```
rule 15 - Reminder: 1 day after missed visit 'Schedule Start Date (SSD): form.calcs.general.next_visit_date || form.calcs.next_visit_date.next_visit_date
For 15 - Reminder: 1 day after missed visit, we're looking in form.calcs.next_visit_date.next_visit_date and finding: 
Error... you can't schedule an alert without a date.
```

**Comment by aleksa-krolls** [comment]
See @ritazagoni  comment on the PR: https://github.com/OpenFn/Miracle-Feet/pull/68

Not sure if @taylordowns2000 or @lakhassane should finish this up?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane who should I assign this issue to?

**Comment by lakhassane** [comment]
@ritazagoni feel free to retest.https://www.openfn.org/projects/pdbznd/runs/r446kgy6

if you look at line 71 of the logs, we are skipping schedule because next_visit_date is empty

**Comment by ritazagoni** [comment]
@lakhassane we have multiple potential paths for `next_visit_date` and one of them has a value: `form.calcs.save.next_visit_date'`. We pick it up successfully in the beginning of the job, see line 5 in the logs. See original value on 193 in the message https://www.openfn.org/projects/pdbznd/messages/m66gmg4b. We somehow fail to use when checking next on line 71 of logs.
