### ISSUE TITLE
Duplication:`Tenotomy` message scheduled 3 times

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#69]
## Describe the bug
[Alert 05](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=23:23), should be sent only once. We schedule it once, then when checking for scheduled alert later we don't seem to find it on Infobip and schedule it once again. `bulkId tenotomy1-da222872-f5b8-428e-947a-1a8a2e60cf31`

## To Reproduce
First scheduling: https://www.openfn.org/projects/pdbznd/runs/ryapz9p6
Second: https://www.openfn.org/projects/pdbznd/runs/rrkgpdg4
Third: https://www.openfn.org/projects/pdbznd/runs/rpd9p3zb

When we re-run either of these runs, the alert with `bulkId tenotomy1-da222872-f5b8-428e-947a-1a8a2e60cf31` should not be scheduled again.

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### adaptor
`language-http`

### state.json
See LP for `Infobip portal`

**Comment by ritazagoni** [comment]
Seeing similar error with `casting-intro-1`. However when that was retried later the scheduled message was found and new one was not scheduled, as expected. Testing before assigning further. 
https://www.openfn.org/projects/pdbznd/runs?dateRange=720&endDate=2021-08-02T13%3A48%3A36.321Z&jobId=&page=1&perPage=10&searchString=casting_intro-1-80b340f3-7b3f-456a-8507-cf2bc13f8ab2&startDate=2021-07-03T13%3A48%3A34.782Z&success=

**Comment by ritazagoni** [comment]
Error remains: `tenotomy` message scheduled again https://www.openfn.org/projects/pdbznd/runs/rd76aj7a

**Comment by aleksa-krolls** [comment]
@ritazagoni on this one... are you able to find the scheduled message in Infobip for tenotomy before running the job again to create a dupe? (wondering if in Infobip we can see the dupes... or only in the OpenFn logs)

@lakhassane adding to bottom of backlog. Let @ritazagoni know if you have any questions once you get to this.

**Comment by ritazagoni** [comment]
The messages are duplicated on Infobip as well. Infobip message IDs: `32695087411003500000`, `32695092461703500000`, `32695120070103500000`

**Comment by lakhassane** [comment]
@ritazagoni could you double check with the API from infobip through postman. I have used the GET to fetch a sms supposedly already schedule but having a response as `Bulk not found`

**Comment by ritazagoni** [comment]
Checking with Infobip

**Comment by aleksa-krolls** [comment]
UPDATE: Infobip API apparently only allows us to GET SMSs scheduled in the last 48 hours... therefore not all SMSs are returned and we were rescheduling. @ritazagoni see email thread with Infobip support. 

Therefore we will now implement logic to check criteria in CommCare to see if treatment changed before trying to schedule... this upstream check should also prevent dupe scheduling.
