### ISSUE TITLE
Improve log for date

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#70]
## Describe the bug
On line 26 of logs of run https://www.openfn.org/projects/pdbznd/runs/rzdpgzam we're logging: `For 03 - Casting Introduction, we're looking in now and finding: 1626949945434`. 
See [this section of the scheduleSms job](https://github.com/OpenFn/Miracle-Feet/blob/fb87753015d447a75807ef7666cc153284dd8208/schedule_sms.js#L508-L510)

I'm not sure what the outputted `1626949945434` string represents. We expect a datetime output (the date of `now`). Can we log it as a date?

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/pdbznd/runs/rzdpgzam

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/fb87753015d447a75807ef7666cc153284dd8208/schedule_sms.js#L508-L510

### adaptor
`language-http`

### state.json
See LP for `Infobip portal`

### To test
Feel free to re-run https://www.openfn.org/projects/pdbznd/runs/rzdpgzam

**Comment by lakhassane** [comment]
@ritazagoni it's done here https://www.openfn.org/projects/pdbznd/runs/rrkmej8e
