### ISSUE TITLE
TypeError [Error]: Cannot destructure property 'key' of 'alert' as it is undefined.

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#73]
## Describe the bug
This seems to be happening across all scenarios where a user is trying to opt out of SMS. See run failure: 
https://www.openfn.org/projects/pdbznd/runs/rn5pyyka

## To Reproduce
Feel free to re-run on prod.

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json
See LP for `Infobip Portal (MiracleFeet)`
https://www.openfn.org/projects/pdbznd/messages/mn58jwnb

## Expected behavior
Should succeed with Infobip actions displayed in run logs.

**Comment by aleksa-krolls** [comment]
@lakhassane Can you please prioritize this one this morning? 
cc @ritazagoni

**Comment by lakhassane** [comment]
@aleksa-krolls @ritazagoni the issue we have a `brace_problems_type: "none"` in the state while we were expecting something to map as an alert. So I made a check to ignore if that's the case

**Comment by aleksa-krolls** [comment]
Thanks @lakhassane !! 

@ritazagoni all runs re-run successfully. Please review on Monday with Mamadou to verify this is the right business logic implemented.

**Comment by aleksa-krolls** [comment]
@ritazagoni please close this issue whenever you've verified everything on your side... thanks!
