### ISSUE TITLE
Schedule SMS-s on Infobip in 6-month increments

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#74]
## Background, context, and business value

In schedule_sms.js we schedule messages on Infobip up to more than 3 years in advance for the SMS campaign `bracing_night`. 
However, the Infobip API changed recently and now it only allows scheduling 6 months in advance. We need to find a way of scheduling SMS-s in 6 month increments.

## The specific request, in as few words as possible

1. Create new job
One way to do this would be to create a new job that
a. Queries the CommCare [List Cases](https://confluence.dimagi.com/pages/viewpage.action?pageId=12224287) API endpoint and finds the `patient` type cases that where `treatment=bracing_night`, `closed=false` (ie. filter for open cases)
b. Runs 1x a month to check these cases and
c. Sends them to the inbox for scheduling

The CommCare List Cases endpoint cannot be filtered by case property, only by the parameters listed [here](https://confluence.dimagi.com/pages/viewpage.action?pageId=12224287) and [here](https://confluence.dimagi.com/display/commcarepublic/Case+Data).

Can we filter these results as much as possible, do the additional filtering by `treatment` after fetching the results, and continue with steps b. and c.? 

2.  Update job `schedule_sms.js` to schedule SMS-s not more than 6 months ahead. 

## state.json

See LP `OpenFn Master CommCare (w/ MiracleFeet, GRS, Empleando Futuros, Tostan)` for CommCare and `Infobip Portal (MiracleFeet)`

## adaptor

`language-commcare`, `language-http`

**Comment by aleksa-krolls** [comment]
@ritazagoni Alternative idea below... and can you put this into a data flow diagram? 
1. GET Forms from CommCare (filtering by submission date range)
2. In OpenFn, filter forms further (e.g., only pull forms where `date_of_visit = XXX`)
3. Extract properties we need from form (`treatment`, `date_of_visit` (?)) to build a new Message... post to OpenFn Inbox
4. Trigger SMS job (Q: same or different job?) to schedule the messages in Infobip 

For MF - When do we start this? Only check data submitted from August 2021 onwards... or should we check historical patients who registered for this treatment 3yrs ago, for example?

**Comment by ritazagoni** [comment]
@aleksa-krolls I thought this through https://lucid.app/lucidchart/9454d9ca-7c35-482d-b9e9-0e41284d1281/edit?page=g.wbzQpEu4vv#

I think the problem with fetching form submissions vs case data is that we need _current_ treatment status, while a case submission might be outdated if an another submission was done later, changing the treatment. And we can'f filter by `case_id`. So it seems like we would need to fetch cases and not submissions.

**Comment by ritazagoni** [comment]
@aleksa-krolls  Another hurdle: for this approach to work, we need to keep checking on Infobip which `bracing_night` messages have been sent to a patient. However, the Infobip API only allows querying the delivery status for 48 hours, and this cannot be extended, see info from Infobip below. This has an impact on our other scheduling logic too. 

> 93 days by default via the web-interface. If needed the retention can be adjusted (not lesser than 72 hours, not longer than three years). Over API the timeframe is of 48 hours. After that period expires, the data is achieved and communication content is deleted. You can request for achieved logs for inspection purposes or any kind of law investigations by contacting Support@infobip.com.

**Comment by ritazagoni** [comment]
Implemented with #77 and #78.
