### ISSUE TITLE
Don't schedule SMS for a list of alerts

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#76]
## The specific request, in as few words as possible

On the Infobip API, we can't schedule SMS-s for more than 6 months ahead anymore... this is a new API limitation. We therefore need to stop scheduling SMS alerts in the [red rows](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=59:106) in the schedule_sms.js https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js job.

## state.json

See LP `Infobip Portal (MiracleFeet)`

## adaptor

`language-http`

**Comment by ritazagoni** [comment]
@lakhassane What's the best way to do this? Should I recreate the Master Mapping Sheet, assigning a new `#Alert` number to the SMS-s that we need to stop scheduling?

**Comment by lakhassane** [comment]
hmm @ritazagoni I think one way to do this is to have a new Master mapping sheet without the red rows. The job won't iterate on them. Let me try to add a new sheet.

**Comment by lakhassane** [comment]
Ah @ritazagoni I don't have access to edit. Can you please: 
1. duplicate the `Master Mapping Table` and rename it maybe to MMT without red rows lol
2. remove the red rows
I will use that new one to update the job.

**Comment by ritazagoni** [comment]
@lakhassane :D here it is https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=1707677033

**Comment by ritazagoni** [comment]
Perfect https://www.openfn.org/projects/pdbznd/runs/r7xpdgy9
