### ISSUE TITLE
Add `SMS_Treatment__c` and `Treatment_Registration_Date__c` and pronoun fields to `Patient`-s in SF

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#77]
## The specific request, in as few words as possible

We want to start using SalesForce Patient attributes to guide SMS scheduling. For this, we need to modify CommCare > Salesforce jobs to add new fields.

Jobs to update:
1. [Add New Patient](https://github.com/OpenFn/Miracle-Feet/blob/master/add_new_patient__UPDATED.js)
2. [Add New Visit](https://github.com/OpenFn/Miracle-Feet/blob/master/add_new_visit__UPDATED.js)

Logic to add:
1. When `treatment != original_treatment`, update SF `Patient` with `SMS_Treatment__c: form.treatment` && `Treatment_Start_Date__c: form.received_on`

2. Map the following fields from CC to SF:
 `form.calcs.sms.pronoun_he_she` --> `Pronoun_he_she__c`
 `form.calcs.sms.pronoun_him_her` --> `Pronoun_him_her__c`
 `form.calcs.sms.pronoun_his_her` --> `Pronoun_his_her__c`

## state.json

See LP `MiracleFeet Salesforce Production`
Example state for [1. Add New Patient](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/patientRegistration_educationalMessage.json)
Example state for [2. Add New Visit](https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/log_visit_details_original_treatment.json)

## adaptor

`language-salesforce`

**Comment by aleksa-krolls** [comment]
@ritazagoni 
1. Can you please link to an example state in both jobs? 
2. Are the mappings the same for both jobs? 
3. We should not be testing in prod... these are new fields we'll need to configure & test in sandbox. Once Beth sets up the sandbox, we can update the cred info & hand-off to Mamadou... I will keep an eye out on email.

**Comment by ritazagoni** [comment]
@aleksa-krolls 
1. Example states added.
2. Yes mappings are the same.
3. Noted

**Comment by ritazagoni** [comment]
hey @elias-ba I'd need your help with a last update here. Could you add to the `Contact` the following mapping in add_new_visit_UPDATED.js ?

**Comment by elias-ba** [comment]
Hey @ritazagoni sure thing. What are the 3 value mappings to add ? Is there a condition to pass for these values to be added to the `Contact` ?

**Comment by ritazagoni** [comment]
hey @elias-ba for mappings see the code block in the comment: `Send_SMS__c`, `SMS_Opt_In__c'` and `SMS_Opt_In_II__c` with paths and values defined:

```
 'Send_SMS__c', state => {
          var sms = dataValue('properties.send_sms')(state);
          var opt = sms && sms=='on' ? true : sms && sms=='off' ? false : ''; 
        return opt; 
        },
       
          'SMS_Opt_In__c', state => {
          var sms = dataValue('properties.sms_opt_in')(state);
          var opt = sms && sms=='yes' ? true : sms && sms=='no' ? false : ''; 
        return opt; 
        },
        
          'SMS_Opt_In_II__c', state => {
          var sms = dataValue('properties.sms_opt_in_educational')(state);
          var opt = sms && sms=='yes' ? true : sms && sms=='no' ? false : ''; 
        return opt; 
        },
```
No other conditions!

**Comment by elias-ba** [comment]
Great @ritazagoni. Doing it right now.

**Comment by elias-ba** [comment]
@ritazagoni are you sure there is `properties` object in the state you gave me to test with ?

**Comment by ritazagoni** [comment]
@elias-ba please use `form.calcs.send_sms`, `form.calcs.sms_opt_in` and `form.calcs.sms_opt_in_educational`

**Comment by elias-ba** [comment]
Thanks @ritazagoni I have tested and it seems to be working fine. I have pushed my changes to GH. Could you test please and let me know if everything is covered ?

**Comment by ritazagoni** [comment]
thanks @elias-ba 
I see an issue: in [this run](https://www.openfn.org/projects/pdbznd/runs/0617fe4c-0047-7edb-bac9-b2252798af6a) we map all of these values as `''` however `sms_opt_in` and `sms_opt_in_educational` have values in [state](https://www.openfn.org/projects/pdbznd/messages/0617fe3b-f878-7360-98f5-4a4d7a04f69e)

**Comment by elias-ba** [comment]
I can't see the run currently. I am having 500 error.
![Screenshot from 2021-11-01 13-07-32](https://user-images.githubusercontent.com/86059666/139676486-e5e114c1-d224-47ad-b651-537afb485076.png)

**Comment by elias-ba** [comment]
@ritazagoni can you confirm that `calcs` have `sms_opt_in` and `sms_opt_in_educational` fields ?

**Comment by ritazagoni** [comment]
sorry! `form.calcs.sms.send_sms` , `form.calcs.sms.sms_opt_in`, `form.calcs.sms.sms_opt_in_educational`

**Comment by elias-ba** [comment]
Thanks

**Comment by elias-ba** [comment]
@ritazagoni I have updated, tested and pushed. Now the values are not empty. Can you check and let me know ?

**Comment by ritazagoni** [comment]
@elias-ba results look good, still testing the entire flow.
Could you please remove the `console.log`-s? :)

**Comment by elias-ba** [comment]
@ritazagoni how are we moving with this ?
