### ISSUE TITLE
Several run failures: SyntaxError: Unexpected token (291:63)

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#79]
## Describe the bug
See run failure: SyntaxError: Unexpected token (291:63)
https://www.openfn.org/projects/pdbznd/runs/06151f30-9abc-762e-b8c8-bd3b63b5f36f

## To Reproduce
Feel free to re-run on prod

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json
See LP for Infobip
msg state: https://www.openfn.org/projects/pdbznd/messages/06151f30-8226-76bb-9f28-dcbebea4a4ba

**Comment by lakhassane** [comment]
@aleksa-krolls re-run here https://www.openfn.org/projects/pdbznd/runs/06152000-8986-73ff-a5c7-76e666673e9f

**Comment by ritazagoni** [comment]
thanks!
