### ISSUE TITLE
Don't schedule SMS-s for more than 90 days ahead

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#93]
## Background, context, and business value

In Infobip we can only query and cancel messages within 90 days from scheduling. In order  to be able to cancel bracing_night messages if needed, let's only schedule them 90 days ahead instead of 6 months.

## The specific request, in as few words as possible

1. In [schedule_sms.js](https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js), we should only schedule [these](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=49:55) bracing night messages. However, we should keep _all_ bracing_night messages in the _json_ object, as we also need to cancel them in this job. 

2. In [1.fetchContact.js](https://github.com/OpenFn/Miracle-Feet/blob/master/1.fetchContact.js) and  [2.scheduleContactSms.js](https://github.com/OpenFn/Miracle-Feet/blob/master/2.scheduleContactSMS.js) use [this](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=262234774) mapping sheet to schedule the updated batches based on `Contact.SMS_Treatment_Start_Date__c` as per below (see [original issue](https://github.com/OpenFn/Miracle-Feet/issues/78) for reference)
```
IF `Contact.SMS_Treatment__c` = 'bracing_night' && 
`Contact.SMS_Treatment_Start_Date__c` = today - 90 days || today - 180 days || today - 270 days ||  today - 360 days || today - 450 days || today - 540 days || today - 630 days || today - 720 days || today - 810 days || today - 900 days || today - 990 days || today - 1080 days || today - 1170 days || today - 1260 days || today - 1350 days
THEN schedule upcoming batch of alerts.
```

1. If today-90: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=56:58
2. if today-180: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=59:62
3. if today-270: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=63:65
4. if today-360: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=66:71
5. if today-450: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=72:74
6. if today-540: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=75:76
7. if today-630: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=77:79
8. if today-720: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=80:83
9. if today-810: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=84:88
10. if today-900: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=89:91
11. if today-990: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=92:95
12. if today-1080: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=96:98
13. if today-1170: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=99:102
14. if today-1260: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=103:105
15. if today-1350: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?pli=1#gid=262234774&range=106:106

## state.json

See LP for  `MiracleFeet Salesforce SMS Sandbox` and `Infobip Portal (MiracleFeet)`

## adaptor

`language-salesforce`, `language-http`

**Comment by aleksa-krolls** [comment]
@ritazagoni @lakhassane moving this to the top of the backlog to prioritize today. Please jump on a call as needed, and let me know if you need assistance!

**Comment by lakhassane** [comment]
@ritazagoni I updated the mapping object, and added spacing for 90 days now!

**Comment by aleksa-krolls** [comment]
@ritazagoni see here for Beth's `bracing_night` testing results: https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=959470187

Please review the SMSs in the logs to make sure the right ones have been scheduled... I'm not sure they all have based on the first one, but I think will be more efficient for you to take a look and then advise if further changes needed here or on another GH issue.

**Comment by ritazagoni** [comment]
Testing done, moved to Prod.
