### ISSUE TITLE
`Disable SMS` job times out

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#95]
## Describe the bug
The disableSMS.js job runs sometimes time out. Could you check if it can be optimised or should we increase run time?

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://openfn.org/projects/miraclefeet/runs/0619516c-7989-7d24-89fa-0092d65ad4e8

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/disableSMS.js

## state.json
See LP for `MiracleFeet SMS Sandbox Salesforce` (contact AK to get verification) 
and `Infobip Portal (MiracleFeet)`

## adaptor
`language-salesforce`
`language-http`

To test, feel free to re-run https://openfn.org/projects/miraclefeet/runs/0619516c-0662-71cb-a03b-b08a2a3997e6 (parent run of timed-out job)

**Comment by lakhassane** [comment]
@taylordowns2000 can you help making this a long-running job?

**Comment by aleksa-krolls** [comment]
@lakhassane before we turn on long-running job setting... why does it take so long to run? Is there anything we can do to optimize the interaction with Infobip? 
cc @ritazagoni @taylordowns2000

**Comment by taylordowns2000** [comment]
all set @lakhassane , thanks for the explanation on slack

**Comment by aleksa-krolls** [comment]
@ritazagoni pls see Slack. Run long enabled... so do we need to re-run this?
