### ISSUE TITLE
`Schedule_SMS` error:  `Cannot read property 'bulkPrefix' of undefined`

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#97]
## Describe the bug
[schedule_sms.js](https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js) job fails with  `Cannot read property 'bulkPrefix' of undefined`.

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://openfn.org/projects/miraclefeet/runs/0619cd68-4723-7668-864e-19b584edb46a

## state.json

See LP for   `Infobip Portal (MiracleFeet)`

## adaptor

 `language-http`

## To test
Feel free to re-run https://openfn.org/projects/miraclefeet/runs/0619cd68-4723-7668-864e-19b584edb46a

**Comment by aleksa-krolls** [comment]
@ritazagoni please don't forget to assign to @lakhassane otherwise these get missed!

**Comment by lakhassane** [comment]
@ritazagoni I made the correction. There was a misunderstanding on my side on the previous issue which triggered this. Corrected now https://openfn.org/projects/miraclefeet/runs/0619e1ea-d1df-755f-b664-da6a8d7445e3
