### ISSUE TITLE
schedule_sms: TypeError [Error] because of new `brace_problems_type` value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#98]
## Describe the bug
See run failure: TypeError [Error]: Cannot destructure property 'key' of 'alert' as it is undefined.
https://www.openfn.org/projects/miraclefeet/runs/0619f6cf-599d-79f7-b444-87015c88a1fd

## To Reproduce
1. Here is a link to a failed run- feel free to run on prod: https://www.openfn.org/projects/miraclefeet/runs/0619f6cf-599d-79f7-b444-87015c88a1fd

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json
`Infobip Portal (MiracleFeet)`
https://www.openfn.org/projects/miraclefeet/messages/0619f6cf-411e-76ba-9079-c3ed93d9cfc6

**Comment by lakhassane** [comment]
@aleksa-krolls here is the correction. it was related to recent changes on `bracing_night` https://www.openfn.org/projects/miraclefeet/runs/0619f8b2-8aee-7d10-a906-a048748dcc75

**Comment by aleksa-krolls** [comment]
thanks, @lakhassane ... that fixed most of them. But now seeing another TypeError from 1 week ago: 
https://www.openfn.org/projects/miraclefeet/runs/06196943-30cc-7827-a9b9-413cc8b8ed0a

@ritazagoni fyi, there were 60 failures from last week that were never reprocessed or addressed. When we resolve an error, let's please try to remember to reprocess _all_ failures and ensure that nothing else has been missed.

**Comment by lakhassane** [comment]
@aleksa-krolls corrected here: https://www.openfn.org/projects/miraclefeet/runs/0619fbd0-89f0-71f4-9fca-44d292c5fe75. 

We had a type_error where `brace_problems_type` was `undefined`.

**Comment by aleksa-krolls** [comment]
Thanks @lakhassane! All SMS runs looking good now :-) cc @ritazagoni

**Comment by aleksa-krolls** [comment]
@lakhassane Seeing one more of these TypeErrors: https://www.openfn.org/projects/miraclefeet/runs/061a4847-9b59-7216-934a-576646c6167f
cc @ritazagoni

**Comment by lakhassane** [comment]
@aleksa-krolls this error is triggered by a new `brace_problems_type` that was not in the mapping: `motion_range`. 
Previously we had only: `not_wearing_enough, child_not_tolerating, family_not_accepting`. Should this be added to the mapping sheet so that I can use it or should we ignore it?

**Comment by ritazagoni** [comment]
thanks @lakhassane I'll check with MiracleFeet, it is indeed new and they might need a new SMS message for it.

**Comment by aleksa-krolls** [comment]
@lakhassane MF confirmed that sometimes they will add options to the `brace_problems_type` question. 
If the value is in the SMS mappings (rn there are 3: `not_wearing_enough, child_not_tolerating, family_not_accepting`)... then we DO want to send the appropriate SMS alert. 

If the value is NOT in the mappings (e.g., `motion_range`) then we can ignore it and not worry about an SMS alert. Therefore, this run should succeed: https://www.openfn.org/projects/miraclefeet/runs/061a4847-9b59-7216-934a-576646c6167f

Let @ritazagoni know if further questions once you dig in on Monday :-)

**Comment by lakhassane** [comment]
@aleksa-krolls I created a list of valid `brace problems type` to check. See run here: https://www.openfn.org/projects/miraclefeet/runs/061aded9-1bb8-7b55-8348-a3e95ba12002

**Comment by ritazagoni** [comment]
Runs reprocessed.
