### ISSUE TITLE
JSON_PARSER_ERROR: Cannot deserialize instance of date from VALUE_STRING value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#99]
## Describe the bug
See run failure with error `JSON_PARSER_ERROR: Cannot deserialize instance of date from VALUE_STRING value  or request may be missing a required field at [line:1, column:406]`

I think something may be going on with date formatting. 

## To Reproduce
Feel free to re-run on prod: 
https://www.openfn.org/projects/miraclefeet/runs/061a8756-3211-7efc-8889-b0c67025fa2f
https://www.openfn.org/projects/miraclefeet/runs/061a8744-2cb6-71d4-9edf-655dacaf9891

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/update_patient_UPDATED.js

### adaptor
salesforce

### state.json
See LP for `MiracleFeet Salesforce Production`

Some example states: 
https://www.openfn.org/projects/miraclefeet/messages/061a8756-27f1-7a82-9118-51968a5ece31
https://www.openfn.org/projects/miraclefeet/messages/061a8744-22d7-714e-aa39-d17fd1534291

## Expected behavior
Several Update Person runs are failing bc of this right now... please correct and re-process the above on prod.

**Comment by aleksa-krolls** [comment]
@elias-ba can you please check out this bug after you've addressed the Itau issue today? Thanks!

**Comment by elias-ba** [comment]
@aleksa-krolls this seems to be fixed and working fine. I have tested locally and on the Platform. See this successful run: https://www.openfn.org/projects/miraclefeet/runs/061a9002-5b79-773b-b849-bc3b39581da2.

Please test and close this issue if everything okay otherwise let me know.

**Comment by aleksa-krolls** [comment]
@elias-ba working great! Thanks so much for the help :D

**Comment by aleksa-krolls** [comment]
@elias-ba I found another instance of this error that is not retrying successfully... can you please look at this run failure and make further changes as needed? 
https://www.openfn.org/projects/miraclefeet/runs/061ae0c5-cd76-7533-bde3-97ee14d5786b

**Comment by aleksa-krolls** [comment]
@elias-ba can you please check this one out tomorrow? Hoping it will be quick. cc @taylordowns2000

**Comment by elias-ba** [comment]
Hey @aleksa-krolls sorry I missed this one today. It's now done. I have tested it locally and in platform, see this run: https://www.openfn.org/projects/miraclefeet/runs/061b0069-cb5c-7ac5-9c5e-672ffd49ce5c. Please test it and close this issue if it's okay, otherwise let me know. Thanks

**Comment by aleksa-krolls** [comment]
Thanks @elias-ba ! And thank you for the suggesting... slowly working on backwards documentation for these older projects... so can you pls let me know what you changed to make this run successfully?

**Comment by elias-ba** [comment]
Welcome @aleksa-krolls. See my comment [here](https://github.com/OpenFn/Miracle-Feet/commit/a3d01c8c887c594a94964c0be11520897ed11479#r61549190) for a detailled explanation of how I made the run successful.
